/* BOXXY user level pack: Alphabet Soup */
(() => {
  "use strict";
  const pack = {
  "format": "boxxy-level-pack",
  "formatVersion": 1,
  "id": "alphabet-soup",
  "title": "ALPHABET SOUP",
  "displayName": "Alphabet Soup",
  "author": "Sam Cornwell",
  "accent": "black",
  "license": "User-authored BOXXY collection",
  "description": "A gruelling level pack featuring A-Z in a Boxxy font, culminating with a challenging pangram: Wizard Quickly Jumps over fix box things",
  "generatedAt": "2026-08-13T20:46:15.084Z",
  "levels": [
    {
      "rank": 1,
      "sourceNumber": "alphabet-soup-1",
      "name": "A is for Apple",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 143,
      "solution": "rrdddlUruuuuulDulldRRurDDDDuuuullllldRRRRurDDDlllUdrrruuulllldRRRurDllllldddddrruUUUddddlluuuuurRRRllllddRldddrruuUUdlluurRllddddRdrUUdlluurRRR",
      "layout": [
        "#########",
        "#       #",
        "# $ *$. #",
        "# *$#.. #",
        "# $ @ . #",
        "# *$*.. #",
        "# $ #$. #",
        "#   #   #",
        "#########"
      ]
    },
    {
      "rank": 2,
      "sourceNumber": "alphabet-soup-2",
      "name": "B is for Ball",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 335,
      "solution": "lllllluuuuuurrrrrrddllllDurrrruullllllddddddrrrrrruulLrrddlllllluuuuuurrrrrrddlllldLrurrrruullllllddRddlddrrrrrruullULuRddrrddlllllluuruuRlddlddrrrrrruullulLullDDuuuurrrrDullllddrrdrrdrrddlllllUdrrrrruullullLulDuuurDlddrruLdlUrrdrrULLLuurrrrrddLLLrddrUlllluuurrrrrddLLrddrddllUUruuruullllldddrrRurDuruullDDrdLLLLrrruuurDldddddrruLdlUUU",
      "layout": [
        "#########",
        "#       #",
        "#.$##$$ #",
        "#.$.... #",
        "#.$$$$$##",
        "#....$. #",
        "#.$##$$ #",
        "#      @#",
        "#########"
      ]
    },
    {
      "rank": 3,
      "sourceNumber": "alphabet-soup-3",
      "name": "C is for Cat",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 228,
      "solution": "uLLLLLrddddddRRRllluRRurDllluRRRlllullddRRRdrUluRlluuuurrdLulDDDDullddrRRdrUluluuurrurrdLLLulDDDDullddrRRRRlluluuurrdLulDDDullddrRRRluluurrurrdLLLulDDDullddrRRululluuRRRRRurDlllldddrUUluRRRllllldRRdrUUluRRRlllddddddLuluRRurDDldR",
      "layout": [
        "#########",
        "#.    $.#",
        "# $ $ $+#",
        "# $ $ $.#",
        "#   $####",
        "# $ $...#",
        "# $ $...#",
        "#.$ $...#",
        "#########"
      ]
    },
    {
      "rank": 4,
      "sourceNumber": "alphabet-soup-4",
      "name": "D is for Dog",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 237,
      "solution": "ulululldLulDDDrUluurrdLulDDrdDDuuuururrdrdrddldldllLuurDuluuururrdLLLulDrrrrrdrddldlULLdlUUUddrrrrruulululllldRRRlldddrrrrruulDrdLLLLdlUUUUruLrrddDuulldddrRRdrUruulDrdLLLLdlUUUUrrddRRuuLrddlluUruLddLrddlluUruLrrddrddLLulDrruuuurDDDrdLLLL",
      "layout": [
        "#######",
        "#...  ##",
        "#.$ $  ##",
        "#.$$ $  #",
        "#. #$ $+#",
        "#.$ $$  #",
        "#. $$  ##",
        "#...  ##",
        "#######"
      ]
    },
    {
      "rank": 5,
      "sourceNumber": "alphabet-soup-5",
      "name": "E is for Egg",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 115,
      "solution": "dLLLUlldRRRRlllluUlDuuuUrurrrRllDDlDRRRllulullddRRRRlllddrrUdlluurRddlUlluuurDrururrdLulDDlllddrrddrrruLLdlUruLLdlU",
      "layout": [
        "#########",
        "#.    $.#",
        "#$  $$  #",
        "# $  ####",
        "#..*....#",
        "# $  ####",
        "#$  $$ @#",
        "#.    $.#",
        "#########"
      ]
    },
    {
      "rank": 6,
      "sourceNumber": "alphabet-soup-6",
      "name": "F is for Fox",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 93,
      "solution": "lLLDlDlluuurluurrDullddddRluurDRRRRlllllddrrUdlluuurdRRRlllldRurDlluuuurrdDDrdLLruuurrurrdLLL",
      "layout": [
        "#########",
        "#   *   #",
        "# **  $ #",
        "#   *####",
        "# $  $.+#",
        "#.$ $####",
        "#  *.#",
        "#  .*#",
        "######"
      ]
    },
    {
      "rank": 7,
      "sourceNumber": "alphabet-soup-7",
      "name": "G is for Golf",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 124,
      "solution": "LLLLdllddDrddrRurrrUdllUdrruLuLrddlldlluRRRUdllldlUUrUUluuRRRRdLullDDDDldRdrrururrddlUUldldlluuuuuurrdLulDDlDDrddlUrdrrurrdL",
      "layout": [
        "#########",
        "#     *@#",
        "#   $ * #",
        "#  ######",
        "# *#....#",
        "#* ##$$$#",
        "#  *    #",
        "#   *   #",
        "#########"
      ]
    },
    {
      "rank": 8,
      "sourceNumber": "alphabet-soup-8",
      "name": "H is for Horse",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 152,
      "solution": "rrRRRllrrlllUdrrruruulDlDRdLLLrrrdrddlUUUUUluRdddlDullulldRRRRurDldRddlUUruLLLulDDlddrruUluRRRdrUUluRdldllluuurDDldRRRurDDldRuullllldddrUUluRRRRurDDDldR",
      "layout": [
        "#########",
        "#   #  .#",
        "#   # $.#",
        "#  $#$ .#",
        "#@  $  .#",
        "#  $#$ .#",
        "#   # $.#",
        "#   #  .#",
        "#########"
      ]
    },
    {
      "rank": 9,
      "sourceNumber": "alphabet-soup-9",
      "name": "I is for Indigo",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 146,
      "solution": "LUdDuuluurRRRDDDDDldRlLLLrUrrruuuuullllddrdrDululuurrrrdddddldlluRuululuurDrrrdddddlluuuUUruLLLrrdddRldddrruuUUUllddddRluurrdDuulllDlDurrddlUluUUU",
      "layout": [
        "#########",
        "#.. $ ..#",
        "##    $##",
        " # *$* #",
        " # $@$ #",
        " # *$* #",
        "##$    ##",
        "#.. $ ..#",
        "#########"
      ]
    },
    {
      "rank": 10,
      "sourceNumber": "alphabet-soup-10",
      "name": "J is for Joy",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 220,
      "solution": "urrrrrdDDDLLLLdlUddrrrlluurrrruuuulldDDuuurrddddlLLLrlddrrULdlUUdrrUrruuuullddDuuurrddddlLLdrdrrULulDrdLLLrruuuuuullldRRurDDDDDrdLLruuuuuurrdLulDDDDDrdLuuuuurrdLulDDDrdLLLrruuurrdLulDrdLrdrUUUluurDlddrUluurrdLLulDDDDrdLL",
      "layout": [
        "#########",
        "#       #",
        "#@$  $  #",
        "####$$$##",
        "#..# $ #",
        "#... $ #",
        "#..$$$ #",
        "#...   #",
        "########"
      ]
    },
    {
      "rank": 11,
      "sourceNumber": "alphabet-soup-11",
      "name": "K is for Kiss",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 150,
      "solution": "rddLDLLLLdlUUUrurDDlddrruLLdlUUddddrrUUruLLdlUrrrrrDLLLLrrrrrddlUruLLLLdlUruLrrrruruulDDDlddrruLLLLulDDrdLururrruuulDDrdLLLulDurdlrdLruuuRRurrdLulDrdL",
      "layout": [
        "#########",
        "#.  ##@ #",
        "#. $# $ #",
        "#.  $ $ #",
        "#.  .$$##",
        "#.   $  #",
        "#. $#   #",
        "#.  ##  #",
        "#########"
      ]
    },
    {
      "rank": 12,
      "sourceNumber": "alphabet-soup-12",
      "name": "L is for Lemon",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 205,
      "solution": "llllLuUUUrDullUdrrUddrDrDululldddrrRuululuurDllluRdddddrrULdlUrUdlluUruulDrrrrDDLruuluurDDlDDuulluuRRlDldRllDrururrdLdLruulldRdrdrUllulldRDRddlUruUUluurrdLdddddrrULdlUUUluluRddrrDulluuurrdLDldDrruUdLdlUruL",
      "layout": [
        "#######",
        "#.   .#",
        "#$.$.$#",
        "#.  $.#",
        "#$ $ $#",
        "#.$ $.#",
        "# .$.$###",
        "#.$   .@#",
        "#########"
      ]
    },
    {
      "rank": 13,
      "sourceNumber": "alphabet-soup-13",
      "name": "M is for Mother",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 124,
      "solution": "uRRdrUUUUUddddllUUUdddrruuLUUdrdddlUUUlDDrdLulDuulrddLLdlUUUUUdRlddddrurruulUdrddlUdlluRRRRurDllllUUUdddrrruuLLrddlluUrDDrdL",
      "layout": [
        "#### ####",
        "#..###..#",
        "# ..#.. #",
        "# $ $ $ #",
        "# $   $ #",
        "# $$ $$ #",
        "# .$ $. #",
        "#  #+#  #",
        "#########"
      ]
    },
    {
      "rank": 14,
      "sourceNumber": "alphabet-soup-14",
      "name": "N is for Night",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 166,
      "solution": "rddddddlluulUUUlullddRRurDDDrddlUUUUlllddrUluuurrddLdlUrdRurDDrddrruuLLrDrdLLrruuuulDDuLLLullddrUluRRdrrrruuulDDrddlluRllllldddrUluurruuullDDuRurDDldRRRdrUdrdLdlUUruL",
      "layout": [
        "#########",
        "#   .#@ #",
        "# $ .#$ #",
        "# $ .#. #",
        "#.$$*$$.#",
        "# .#. $ #",
        "# $#. $ #",
        "#  #.   #",
        "#########"
      ]
    },
    {
      "rank": 15,
      "sourceNumber": "alphabet-soup-15",
      "name": "O is for Olive",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 135,
      "solution": "rrUruuulLuulldDllddrRlluurrDDuuuurrddrrdddllUUULLddRluurrdDuulluurrrDulllddddlluuuRurrrrdrddLruulullDulldlddRluururrrrdrddddldllllUdrrU",
      "layout": [
        " #######",
        "##     ##",
        "# $.$.$ #",
        "# .$.$. #",
        "# $.#.$ #",
        "# .$.$. #",
        "# $.$.$ #",
        "##  @  ##",
        " #######"
      ]
    },
    {
      "rank": 16,
      "sourceNumber": "alphabet-soup-16",
      "name": "P is for Pumpkin",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 99,
      "solution": "luulllddDDllUUddrUUdrdrrUUruLddLdrrUUruLdlUruLdddrdrUUdlldllUUddllddrUUluRRRdrUUddlllddrUUluRRRdrUU",
      "layout": [
        " #######",
        "##  .  ##",
        "#.......#",
        "#   #  @#",
        "#$$$$$$$#",
        "#       #",
        "# $ #####",
        "#   #",
        "#####"
      ]
    },
    {
      "rank": 17,
      "sourceNumber": "alphabet-soup-17",
      "name": "Q is for Quack",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 128,
      "solution": "llluUrUrUdldllluurDDldRurDldRRRlluurDldRuuururuullllDDDDldRRurDuurRurDDulllLdlUUdrrrruuulDDrdLLdlluRRRRurDuulullldRRurDDldRuullD",
      "layout": [
        " #######",
        "##     ##",
        "# * $   #",
        "#  # $  #",
        "# $ * $.#",
        "#  $ # .#",
        "#   $ #.#",
        "##  ..+##",
        " #######"
      ]
    },
    {
      "rank": 18,
      "sourceNumber": "alphabet-soup-18",
      "name": "R is for Rabbit",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 254,
      "solution": "ruuuuuRRdrruLLLLdlldRurDDuuurrrrdddLruulldDuuulldlluRRRRllddRluurrdrrddllUdrUllllldddrrUUUlldRurDuluurrrDulllddrrRdrruLLLLdlUrrrdLLrrrddlUruLrruuLdllllluurrrrDullllddrrrRurDDDldRuuuulullDullddrRRRurDllllldddrrUUddlluuurRRRllllddRdrUUdlluurRuulDrurrdrruLL",
      "layout": [
        " #######",
        "##* * *##",
        "#   *   #",
        "#   #   #",
        "# * * * #",
        "# * * * #",
        "# $ #  ##",
        "# @ #  .#",
        "#########"
      ]
    },
    {
      "rank": 19,
      "sourceNumber": "alphabet-soup-19",
      "name": "S is for Snake",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 164,
      "solution": "lUdDrurDrrddllUdllUUrRulullluurrrDDDrdddlluuRlUruuulllddrRdrUllluurrDDrddlUruLddddrrrruuuLLrrdddlllluurUrDurrdLLulldddlluRdrrrrUruulllluuulldRurrrdDuurrdLullllldddR",
      "layout": [
        "#########",
        "#       #",
        "# $.*.$ #",
        "# .$.$###",
        "# $.@.$ #",
        "###$.$. #",
        "# $.*.$ #",
        "#       #",
        "#########"
      ]
    },
    {
      "rank": 20,
      "sourceNumber": "alphabet-soup-20",
      "name": "T is for Train",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 113,
      "solution": "rrddlUruLLLLddrUluRRRRdlLullddrUdRllddrRUUluRurrddLUrdddLLuUUdddDurrddlLuuuullddRluurrrrddlUdDuLuullddRRurDruuulD",
      "layout": [
        "#########",
        "#. .+. .#",
        "## $$$ ##",
        " #  $  #",
        " # *$* #",
        " #  $  #",
        " # *$* #",
        " # . . #",
        " #######"
      ]
    },
    {
      "rank": 21,
      "sourceNumber": "alphabet-soup-21",
      "name": "U is for Unicorn",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 121,
      "solution": "rddddLdLdllUlUdrdrruLULUUddrRdrUlUUddlluullddRRRdrruruulldDlllUUluurrDDDldRRRuurrddLLLLrrrruuuullDDDurrddlLuLrurruLulDDrD",
      "layout": [
        "#########",
        "#   # @ #",
        "# . # $ #",
        "#   #   #",
        "#  * *  #",
        "# * * * #",
        "#* * * *#",
        "# *   * #",
        "#########"
      ]
    },
    {
      "rank": 22,
      "sourceNumber": "alphabet-soup-22",
      "name": "V is for Voice",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 165,
      "solution": "uluuullddRluurrdDllddrdrdrruruLddlluluUddrdrrururuuLrddlluUdlLuuullddRlddrdrdrruuullUdrrurruullDurrdddLLrruuulDDrdLdlddlluRlluluurrdDuulluurrDulldddRdrRRllluuluurDDD",
      "layout": [
        "#########",
        "#   #   #",
        "# $ # $ #",
        "# $.#.$ #",
        "# $...$ #",
        "# .$@$. #",
        "## .$. ##",
        " ##   ##",
        "  #####"
      ]
    },
    {
      "rank": 23,
      "sourceNumber": "alphabet-soup-23",
      "name": "W is for Water",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 79,
      "solution": "dldRRurrddlUruLLdlUddLullddRdrUUUddlUluRRRurrdLrdLLrdLLdlUluurDuuRRRdrruulDDrdL",
      "layout": [
        "#########",
        "#  #+#  #",
        "#       #",
        "#   *   #",
        "#  * *  #",
        "# * $ * #",
        "#*  #  *#",
        "#  ###  #",
        "#### ####"
      ]
    },
    {
      "rank": 24,
      "sourceNumber": "alphabet-soup-24",
      "name": "X is for Xylophone",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 134,
      "solution": "llUdrrrrUdllllDurrrrDulllluRdrUllddRurDurruLdllldlddrrUUruLulluurrDDDDllddrrUUrurrdLLLrrruuruullDDrddlluRdrrddllUUllddlluuRRRRddrruuLL",
      "layout": [
        "#########",
        "#   #   #",
        "# .$.$. #",
        "# $$.$$ #",
        "##..@..##",
        "# $$.$$ #",
        "# .$.$. #",
        "#   #   #",
        "#########"
      ]
    },
    {
      "rank": 25,
      "sourceNumber": "alphabet-soup-25",
      "name": "Y is for Yellow",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 205,
      "solution": "llldRdLLLdlUUrdrrdLuruurrrddddddllluUUlulldRRdrddrrruuuuuullddLLdlUUddrdrUlrdddrrruuulLLdruuLLLdlUrrrddlUrudlruLdlUrruurrrddLLLLLrruurrDrdLLLLddrddlUUUrrrrdddllUUluurrdLLLLrdddlluRdrUUruLrrrrdLLLddrrUUUruL",
      "layout": [
        "#########",
        "#..#   @#",
        "#..# $  #",
        "#...$.$ #",
        "#..$ $  #",
        "###.$ $ #",
        "# $$ $$ #",
        "#       #",
        "#########"
      ]
    },
    {
      "rank": 26,
      "sourceNumber": "alphabet-soup-26",
      "name": "Z is for Zebra",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 137,
      "solution": "lllllrUdlluRuRurUURRulLLLrrdLLrrddrUUluRRdlddlldlddrUdrruLUUUruLLrdddddlluRdrUUUUUruLLrdddddlluRdrUUUUluRRddlddddrrruLLdlUUUrudlUruulldRR",
      "layout": [
        "#########",
        "#..   ..#",
        "#..$ $..#",
        "####$$ ##",
        " ##   ##",
        "##   ####",
        "# $$$ $ #",
        "#      @#",
        "#########"
      ]
    },
    {
      "rank": 27,
      "sourceNumber": "alphabet-soup-27",
      "name": "Wizard Quickly Jumps Five Box Things",
      "author": "Sam Cornwell",
      "tier": "ALPHABET SOUP",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 4878,
      "solution": "LUluurRRRlllllllldldLdLddldlddlldRRldRRluurDrDDDuuulldRurDDulldRlLdDldRRllluluuurDDRlldRurDldRRuUUruulDDDDlluuRRurrdLuuuuururuuUluRdrUllrrddRlullldRRurlllddRdrUUluurrrdddLLdurUlluurDurrrrddLuuurrrrddrdrRUrUdldlluUruLLdrddrUrlUdrruLuLLddrrdDrddlUUUddllddddddlrdLdLdllUlUUUdddrRULUlluuurrdDDDrRULrrrdLLruruuulldDuurDDDuuuruuurruulrlludrrUdddlUruulldDlDRdLuruuulDDDurrrudddrrrrrrUdlluRuRurUULLruRRRlldRRllddrUUruLLLLrrdddldlddrUdrrlruLUUUUruLLrddddddlluuRlddrruUUUruLLrdddddlluRdrUUUUUluRRdldddddrrruLLdlUUUUruulldRRdlddddlllllluluuLulDuuurrDLulDrrrllddllddrRurrddlUlldRRRRRRRRllllllllruuuuurrdDDDldRRRRurrdLLLLrrrurrrdLLLLLrrrrrrrrrrrddLLLLddddddRRRllluRRRllluRRRlllulldRRRRlllldRRRRlllldRRRRlluuuuuurrdLulDDDldRRluuurrdLulDDDldRRluuurDDDldRluuuuurrurrddLLLulDDDDrdLLruuuuuuLrrrrruulluuuuuurrrrlllldddRRRRurDDrddllUdrruuulllllldddrruUddlluuurRRRurDuuulDulldRRurDullllldRRRRlllrllddrrUdlluurRllddddRdrUUUUddddddlldRdrUUUUddlldlddllluRRRRRllllluRRRRRuruulluuurrdDDDuuuulluuurrDDullddrRRRlluuurrrrddddddrruuuuurrRRdddddrrddlllllrddLDLLLLulDDDrdrUluurrdLLulDrurrrrDLLLLrrrrrddlUruLLLLdlUUruLdlUUrurDDlddrruLdlUUruLdddrrrruuruulDDDlddrruLLLLdlUUruLdrrrruulDrdLLLLurRdrruulDrdLruuurrrrddlrrDrDuUrUdlddrUlllDlddRRRRRRRRRRRllllllllllluuruulUrdddlUdddrrrrrlUdlllluuuruuurDlddrruLdlUdrldlddrUUluRurrddLLulDDrdrUluuurrdLrdLLruulDDrddrrrrrrrrruUlUdrddllllllllUdrrrrrrrruurUrrdddlLLLLLLLLLrrrrrrruululluuuuuururuulululldLurrrdrdrddldldlllluuuuUddrUUrurrdLLLddlddrUluururrdLLrurrrdrddlUlUdrruLuLLdlUdrurrddduuLLrrdddlUUdLLLdlUrrrrruuulllldDuurrrrdddlllLrrDrdLLLrruLLuuuurrdDDDrdLLuuluuRurDDDDrdLuuuuurDldRRdldddddddrrdrruLrrruuullldDLLdlUUrdrruurrdrddlldllUdrruLuLLdlUrrrddlUruLdlUUddrruuurrdDrdLLLdlUruLdlUdrrrruLLLLrruurDrdLLLrddddrUUUruLLddddrrruLdlUUUddrUruLLLLLrrdddlUUruLdddlluRdrUdllllllulldRRlluuurDluuuuuulluuuurruLLLLdduurrrrddLuullrrddDDldRuuuululldddRRllrrdrUllluuurrrdlDuulldddrRlluulluRRlldddRRllddrUdllluuuuuullllllddddddllllllllddLLLddddDrdLurrrruuuUluRddddddlLLruuuUUruLLdlddRlddrruUUUluRRldddRluurrdDDDldRddrddldrdLdLdllUlUUUluullldDDDLLLLdlUddrrrrrlllluurrrruuuulldDDuuurrddddlLLLddrrULdlUUdrrUrruuuullddDuuurrddddlLLrrruLruuullddDrdLddrUluurrdLulDDrdLLLrruuuuuullldRRurDDDDDrdLLruuuuuurrdLulDDDDrdLLLrruuuuurrddLulDDDrdLLrrdrUUUUluurrdLulDDDDDrdLLuuuuurrrurrddddrdrdrruLULUUddrRUrruuulldDDDlluRdrUUddlluulluurrDDldRRRurrddLLrruLLLrrruuullDDuurDDDuururrrdlddddrRlluuuurrddrdDuulLrrddllluUUUddrUUdldddrUUUdrrruLdlUdrdLulDrdruurRUUddDrUUUdddddlUUUUllddRurrddlUUruLdlUddldRurrddrruuUUddrrUUUluRddddrrrlUUruLdddlllUUdlddRdrUUUUdRdrUUddrUUddrUUrruurrdLulDrdLLLrruurrrrdLLrdddRddrruuuLLdlUUdlrrrrdddlluululUdrdrddlluUddlluRdrrrrruuLulDrrllluullluurrrrrldDDldlUrrrdLrrddlUruulluuullllddrRlllrdRRRllluuurDudDldRluuurrrrrrdLulllllddllddlluuRRRRlldlldllddddrrrrddllllDurrrruullllllddddddrrrrrruulLrrddlllllluuuuuurrrrrrddlllldLrurrrruullllllddRddlddrrrrrruullULuRddrrddlllllluuruuRlddlddrrrrrruullulLullDDuuuurrrrDullllddrrdrrdrrddlllllUdrrrrruullullLulDuuurDlddrruLdlUrrdrrULLLuurrrrrddLLLrddrUlllluuurrrrrddLLrddrddllUUruuruullllldddrrRurDuruullDDrdLLLLrrruuurDldddddrruLdlUUUllluuulllLLLDllDlddRddrrrRlllluuluurDRRRRllllDurrdLddrUUluRRlluurDldRulluuRRRRdLulllddlddDudRRdrUUddrruLLdlUUdlluuuUruLLLrrrrrrdLLLulDDuullddddldldllululuuuulllDDDDDldRlLLLrrrruuuuullDDDDldRRluuuuulldddDrlrrrruuLruulldDDDldRuuuuullulllllduLLDDDrDuRRlllulldRRRRlllDDldRuuurrdLLrluluuuddrruurrrrrrrrRlllllllldldlluRluRRRdLurRRRRRlldLLLurrrrrRdrruLLLLLLLrrrrrrdrrruLLLLdddddrruuLrddlluUUUrrrurrrrrrdddrruuuRRRRllddLrddldldllululuuuurrdddrrUdlluuullddddrdrRlluluuuurrdddDuuuullddRDuluurDDldRRdrRuLrurrdLLrruuullDDrruLulDurrrrdrruLdddDrddlUUddddldllldddDrdLurrrruuuUluRddddddlLLuluuuuullldddllLLDlrurrrdDldRuuullldlluRRRRRurDDldlUruLLLdlluRRRRRurDllrruuulDDrdLLLLdlluRRRRRuulDrdLLLdlluRRRRdrUluRdlllldddrUUluRRRdrUUluRurrrrrRllllllddldllluurDldRRRdrUUUluRRRRRllllldddllluululllddlUruLLLLddrUluRRRRRRRlllddulLullddrUdlddddrrrruulUUUruLdlldRurrddlUUdlllddrRDulluurrrrddddlLrrlluuUrrdLDlUlluurRurDDDlUdlluurRurDururrrddrruuLLLrrdddrrrruuurrrrddurruLLLLrrrdrrruLLLLdddddrrrruullDDrdLuuuLrddlluUUUddrrUUruLddddddrrrrruuuuuRRdrUllldRlddrUUluurrdrdDDuuuddLruulullddrRdrUlllddddrUluuurrdLrrdDuulluluurDldRurDldRurDDrddrruuLruulDLrrdddlluRUruulDlDlUrrrdLLrddlUUruLrruuulDDrddlddrUUUUlDuuurDDldlddrUUUruulDurrrdddDrddrRRurlUdrrULuLrddlUddllluRRRurrddLUUdlllluUduUddddlUUruuluurDDDDldRuuuuurrrdLLulDDlDDrddlUdrrrurrdLurdrrrrrrrrruulLuluLuurrrruuluURurDuuuLrRlddrrDulluululldlldddlLddlluUlluurRuurrdDuulldRurrlldldllddrUdrddrruLrurruulDrddLdllllUluuuuRurrrrDrrrurrdDuullddRDDlddrrUdlluuruuluurrdrdduurDuurrddLruulldlddLDruuurudldLrururrddlLullddrUrrddrddlUULUUrruullDurrddlLdduurDDrddllUUruulDlruuurDDldDrrddllUUUUruulDDDlluuRRddDrrddllUUUUrruullDDullddrUluullddRRddllddrrUUddddlllldddDRurDlluuuulldddRRdrUllluuddrrrdrrrddllllUUruLdddlludrruuuuuurrdDDuuurrdullllddddddlluRdrrrrruulLrrddlUruuLLuuulldddRluuurrrrdLullllldRlddR",
      "layout": [
        "    ###############################################",
        "    #  #.#   .. $ ..#..   ..#       ##* * *##...  ##",
        "    #       ##    $##..$ $..# $ *$. #   *   #.$ $  ##",
        "    #   *   ## *$* #####$$ ## *$#.. #   #   #.$$ $  #",
        "    #  * *  ## $@$ ####   ### $   . # * * * #. #$ $.#",
        "    # * $ * ## *$* ###   #### *$*.. # * * * #.$ $$  #",
        "    #*  #  *##$    ## $$$ $ # $ #$. # $ #  ##. $$  ##",
        "    #  ###  #.. $ ..            #       #  .#...  ##",
        " #### ######### ##### ######### ########### ##### #######",
        "##     ##   #   #.. $ ..#.    $.#.  ##   .   .###..#    #",
        "# * $   # . # $ ##    $## $ $ $.#. $# $ #$.$.$###..# $  #",
        "#  # $  #   #   ## *$* ## $ $ $.#.  $ $ #.  $.###...$.$ #",
        "# $ * $.#  * *  ## $ $ ##   $####.  .$$##$ $ $###..$ $  #",
        "#  $ # .# * * * ## * * ## $ $...#.   $  #.$ $.#####.$ $ #",
        "#   $ #.#* * * *##$    ## $ $...#. $#   # .$.$### $$ $$ #",
        "##  ...## *   * #.. $  .#.$ $...#.  ##  #.$   .         #",
        " ##################### ##################################",
        "        #           #    ..###..##  .  ##       #",
        "        # $  $  # . # $ # ..#.. #.......# $.*.$ #",
        "        ####$$$##   #   # $ $ $ #   #     .$.$###",
        "        #..# $ ##  * *  # $   $ #$$$$$$$# $. .$ #",
        "        #... $ ## * * * # $$ $$ #       ###$.$. #",
        "        #..$$$ ##* * * *# .$ $. # $ ##### $.*.$ #",
        "        #...   ## *   * #  #.#      #####       #",
        "################################### #####################",
        "#   *    .. $       #    .    $.        ##     ##   #   #",
        "# **  $ ##    $## $ # $ #$  $$  #.$##$$ # $.$.$   .$.$. #",
        "#   *##### *$* ## $.#.$ # $  ####.$.... # .$.$. # $$.$$ #",
        "# $  $..## $ $ ## $...$ #..*....#.$$$$$## $.#.$ ##.. ..##",
        "#.$ $##### * * ## .$ $. # $  ####....$. # .$.$. # $$.$$ #",
        "#  *.#####$    ### .$. ##$  $$  #.$##$$ # $.$.$ # .$.$. #",
        "#  .*####.. $...###   ###.    $.#       ##     ##   #   #",
        "########################## ######################## #####",
        "    #. ... .    #  . ...$  .#   .#        * #       #",
        "    ## $$$ ##   # $.##    $## $ .#$ #   $ * # $.*.$ #",
        "     #  $  ##  $#$ .## *$* ## $ .#. #  ###### .$.$###",
        "     # *$* ##   $  .## $   ##.$$*$$.# *#....# $. .$ #",
        "     #  $  ##  $#$ .## *$* ## .#. $ #* ##$$$###$.$. #",
        "     # *$* ##   # $.##$    ## $#. $ #  *    # $.*.$ #",
        "     # . . ##   #  .#...$      #.   #   *           #",
        "     ################################################"
      ]
    }
  ]
};
  const current = Array.isArray(window.BOXXY_LEVEL_PACKS) ? window.BOXXY_LEVEL_PACKS : [];
  window.BOXXY_LEVEL_PACKS = [...current.filter(item => item?.id !== pack.id), pack];
})();
