/* BOXXY user level pack: Starry Night */
(() => {
  "use strict";
  const pack = {
  "format": "boxxy-level-pack",
  "formatVersion": 1,
  "id": "starry-night",
  "title": "STARRY NIGHT",
  "displayName": "Starry Night",
  "author": "Sam Cornwell",
  "accent": "yellow",
  "license": "User-authored BOXXY collection",
  "description": "Built around the X pentomino — five squares arranged in a simple star-like cross. Its four-way symmetry lets it grow into larger formations, break apart and rebuild, and shift, rotate and reshape into new patterns. A tribute to a famous artist is waiting among the stars on Level 25.",
  "generatedAt": "2026-08-25T21:16:09.619Z",
  "levels": [
    {
      "rank": 1,
      "sourceNumber": "starry-night-1",
      "name": "Shaula",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 37,
      "solution": "UrldDuLurrrdLrddlUlluurDRllrlddRUrrdL",
      "layout": [
        "#######",
        "#  .  #",
        "#  $  #",
        "#.$+$.#",
        "#  $$ #",
        "#  .  #",
        "#######"
      ]
    },
    {
      "rank": 2,
      "sourceNumber": "starry-night-2",
      "name": "Castor",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 14,
      "solution": "RDrdDLdlLUluUR",
      "layout": [
        "#######",
        "#. @$.#",
        "#$$.$ #",
        "# .*. #",
        "# $.$$#",
        "#.$  .#",
        "#######"
      ]
    },
    {
      "rank": 3,
      "sourceNumber": "starry-night-3",
      "name": "Adhara",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 44,
      "solution": "lLLdlDDrdRRlluluururrrdDulLLrrDDLLUUrDrdLulD",
      "layout": [
        "#######",
        "#..$ @#",
        "#. $  #",
        "#$$$$$#",
        "#. $ .#",
        "#..$..#",
        "#######"
      ]
    },
    {
      "rank": 4,
      "sourceNumber": "starry-night-4",
      "name": "Regulus",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 72,
      "solution": "lLLrrrdLullDlDDuururrrdDuullldRRdrUllllddRUluRurrdLLdddRRUUddlluuurRddLL",
      "layout": [
        "#######",
        "#. $ +#",
        "#.$ $.#",
        "#$ # $#",
        "#.$ $.#",
        "#. $ .#",
        "#######"
      ]
    },
    {
      "rank": 5,
      "sourceNumber": "starry-night-5",
      "name": "Mimosa",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 53,
      "solution": "uurRllddrRRuruuulLLddDuuurrrdddldlLrruruLULuRddddlluR",
      "layout": [
        "#######",
        "#. $ .#",
        "# .$$ #",
        "#  *  #",
        "# $$. #",
        "#+ $ .#",
        "#######"
      ]
    },
    {
      "rank": 6,
      "sourceNumber": "starry-night-6",
      "name": "Deneb",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 94,
      "solution": "dLullllDlddddRdrrrrUlUdrruuulLruullldDulldddrRDlrldRlluuuuurrdLulDuurrrrrddlUruLrrdddddlluRdrU",
      "layout": [
        "#########",
        "#   .  @#",
        "# $ * $ #",
        "#  $.$  #",
        "#.*.*.*.#",
        "#  $.$  #",
        "# $ * $ #",
        "#   .   #",
        "#########"
      ]
    },
    {
      "rank": 7,
      "sourceNumber": "starry-night-7",
      "name": "Fomalhaut",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 110,
      "solution": "llllDurrrrddLLddlluUUdddrruurrddddlllllluuuuuurRRRRDullldddRluuurrrdrdddLLrruuulullllldRldddddrrUUddlluRdrrrrU",
      "layout": [
        "#########",
        "#      +#",
        "# $*#*$ #",
        "# * . * #",
        "# #.$.# #",
        "# * . * #",
        "# $*#*$ #",
        "#       #",
        "#########"
      ]
    },
    {
      "rank": 8,
      "sourceNumber": "starry-night-8",
      "name": "Pollux",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 138,
      "solution": "lllddDDuuuurrddDDrddlUUUUddddllUUUUddddlluuUUddddrruuuRldddlluuuuluurrrrrrddlDDulldLrurruruullllllddrdDrruuRlddlluuluurrrDDLDldlddrrruuLrR",
      "layout": [
        "#########",
        "#      @#",
        "# .# #. #",
        "# .$ $. #",
        "##$$*$$##",
        "# .$ $. #",
        "# .# #. #",
        "#       #",
        "#########"
      ]
    },
    {
      "rank": 9,
      "sourceNumber": "starry-night-9",
      "name": "Spica",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 195,
      "solution": "llLLddlluuRRRRRlllllddDDrrddllUUUUUdddrrddRRuurrddLLLLLrrruurrUUlluulldRldllddrrddrruurruullUluRddrrddllUUUddRdrUlululldRRllllddrrUdlluurRRlddddrruuuUllddRlddrruUUdlllluRurDRdrddlluRurDldRRluuruL",
      "layout": [
        "#########",
        "#.  $..+#",
        "# # $.#.#",
        "#   $...#",
        "#$$$*$$$#",
        "#  .$   #",
        "# # $ # #",
        "#.  $  .#",
        "#########"
      ]
    },
    {
      "rank": 10,
      "sourceNumber": "starry-night-10",
      "name": "Antares",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 201,
      "solution": "ddDDLLrddlLLUUdlluUURuurRRlllddlddRluurDDuuuurrrDDlLrruullldDlddrUUrrrurrdddllDLrruruuulldDuurrddLruulldllllddddRUUluurrrrRdddllLLdlUruUluRRRlldddrrrruuuulullllDurrDurDrrruLdddddlllluuuUluRdrrrrdddddrU",
      "layout": [
        "#########",
        "#  .$. @#",
        "#  $$$  #",
        "#.$...$.#",
        "#$$.#.$$#",
        "#.$...$.#",
        "#  $$$  #",
        "#  .$.  #",
        "#########"
      ]
    },
    {
      "rank": 11,
      "sourceNumber": "starry-night-11",
      "name": "Aldebaran",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 93,
      "solution": "dddlLLddRRdrUllluuUUruLdddddrrdrddllluUUllDDldRllluuuuddddrluuuuuuuurrrdDDLLulDDDrRRdddllluUU",
      "layout": [
        "###########",
        "#    .   @#",
        "# #  *  # #",
        "#  #$*$#  #",
        "#  $ . $  #",
        "#.**.#.**.#",
        "#  $ . $  #",
        "#  #$*$#  #",
        "# #  *  # #",
        "#    .    #",
        "###########"
      ]
    },
    {
      "rank": 12,
      "sourceNumber": "starry-night-12",
      "name": "Acrux",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 349,
      "solution": "ddDuuullLLLdldDDDuRRlluuururrrrrdddLruuullllldldddrddrRRRlllluuluuururDDulldddrddrrrUdllUluluuurrurDldRullldRurrurrrdddlUUruLLLdlluRRRRurDDDldRlDDrrddllUUUUUUruLLLLdlldddrdrRRdrUUUUUruLdddddlllluUluuluurDDDDrddlUruLddldRRRurDulluuluuuRRdrUdRRurrdLLLLulldRurDllDDDldRRRRllluuuurruRdrruulDlllldddddrrrdrdrruulUUUUruLLLLLdlluurDrrrrrdddddrdLLLLLullddrU",
      "layout": [
        "###########",
        "#   #.#   #",
        "#    $  @ #",
        "#  .$$$.  #",
        "## $...$ ##",
        "#.$$.#.$$.#",
        "## $...$ ##",
        "#  .$$$.  #",
        "#    $    #",
        "#   #.#   #",
        "###########"
      ]
    },
    {
      "rank": 13,
      "sourceNumber": "starry-night-13",
      "name": "Altair",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 657,
      "solution": "urrdDDrddlUUUUrrurrrdddddddldlllllluluuuuuururRRRRllldddrrddDuuulluuullldddrUldddddrdrruUUUUUdddddrdrrrruuuuuuulLLrrrddlddLLLulDDuuuuLrdrrUdddrrrddldlllllluUUUluuuurrrrrrdrrddlUdddlluuuRldddrruuLulDDldRRRurDDuuuuLdlUldllddLLdddrrrrrruUUUUlllldddLulDrrurrdRullllldlddrrrrrrruUlulllllulDDrrrurrrdrddlllllUUruLdlluuuuuurrrrrDDDuuullDDDDrdrrdrddllllluuuRururuuurDDldllddldddrrrrruuruuulLLLruuullddDuuRRurDDldRuuullllllddddddrrddrrrrruuruuuuLLdlUruullllllddRRlluurrrrrrddldllUdrrrurrddddllDruruuuullldllulllddddrrddllUUUUUUddddrDldRuuluuuurrrdrrrurrddddlddrUlululLuululllddddrruRldlluuuurrrdrrruuullllllDDDDDuuurrrdrrrurruuLDldRlldllulllddrURRllluuurrDDrdLuLUluR",
      "layout": [
        "###########",
        "#  .   .  #",
        "# @$. .$  #",
        "#.$$$#$$$.#",
        "# .$ . $. #",
        "#  #. .#  #",
        "# .$ . $. #",
        "#.$$$#$$$.#",
        "#  $. .$  #",
        "#  .   .  #",
        "###########"
      ]
    },
    {
      "rank": 14,
      "sourceNumber": "starry-night-14",
      "name": "Hadar",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 222,
      "solution": "llllddddrruUlluurDurrDrdddrrrrlluUddrruuuulDullDurrruuuulldDrrddddddlluuUrruuulDullDurrrdddddduLdlUUdduLdlUUddlluRdrUdrrrruuulDrdLLLdllllluuuuuuuurrdRurrDullddDuuurDDuurrrrdLLLulDlullldRRRlldRlldRlddddduRUUluRddddrruLdlUUU",
      "layout": [
        "###########",
        "#         #",
        "# $ $.$ $ #",
        "#  $...$  #",
        "# $.$.$.$ #",
        "# ...@... #",
        "# $.$.$.$ #",
        "#  $...$  #",
        "# $ $.$ $ #",
        "#         #",
        "###########"
      ]
    },
    {
      "rank": 15,
      "sourceNumber": "starry-night-15",
      "name": "Betelgeuse",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 585,
      "solution": "lluRldlluuuUUUUddddRuluRldddddrrruuRuUrRlllUdrrruUddllluLUUddrdrddldlLrruruululuuRuRRRllldlddrdrddlddrrrrruuuUUdddddllllllllUUUUUddddrrruruululuuLrddrdrrrdDDuuullddlddrrRRluuuullluluururrrDDDDDDDuuullddlddrrRuRluuuuRluuuRldRlddddRlullddDldRuuuurrdddLLulDrdLLrrurruuuurDrDullllddldllluuuuRlddddrrrruuulDDrddlluRRRluuurrddDlluulLrrurruuuullldDDDDDDuuuuLLrruuuLrrrrddlUruLLLdddddlLulDDDrrrrrruuurrdLullldddrruUruLLLdllluurrDrdLLLulDrrruuuuRRdrUluRllldddddddlUruuullddRdrUUUUluRRRdrUdddddLLdlUUUUUluRRldddrrruulUdLulDDDrdLLLrruuurrDullddrRRurDldRuullLulDDDDrdLLLruuUluRdrUUUrrdddDDrdLLLulD",
      "layout": [
        "###########",
        "#....$....#",
        "#.$ $ $ $.#",
        "#.#$ $ $#.#",
        "#.$ $ $ $.#",
        "#$ $ $ $ $#",
        "#.$ $ $ $.#",
        "#.#$ $ $#.#",
        "#.$ $ $ $.#",
        "#....@....#",
        "###########"
      ]
    },
    {
      "rank": 16,
      "sourceNumber": "starry-night-16",
      "name": "Achernar",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 188,
      "solution": "lUdrrURdllluLrUddrruULDlluRdrUUddldRRRRRllllllllluuuuRluuRUldddrDuURRllluurDRllddrRuLulDDDDDuuuuuuuuurrrrDurrDRullldLrRlDurDDuuurrdLDlUlrruLLLLLrrrrrrrrrddddLUrdddLDuLrruulLrDLLrdRdrUUUUUU",
      "layout": [
        "#############",
        "#.         .#",
        "# #.$$$$$.# #",
        "# .#  $  #. #",
        "# $ #. .# $ #",
        "# $ .#.#. $ #",
        "# $$ .#. $$ #",
        "# $ .#.#. $ #",
        "# $ #. .# $ #",
        "# .#  $  #. #",
        "# #.$$$$$.# #",
        "#.    @    .#",
        "#############"
      ]
    },
    {
      "rank": 17,
      "sourceNumber": "starry-night-17",
      "name": "Procyon",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 919,
      "solution": "lddrdrrurrdDuulldllddrrdrrRRllllulluurrurrdrrurrrdddlLLdllDurrurrruuullldRuruuulllllllldDDDDldRuurrurrUdlldlluuuurrdLulDDDDrrurrdrrrurrdddllldRurrddlUruuuullldlluRRRllllldlluuurrrurDDullllddRRdRRRurrdLLLLLulllddddddrRRllluuuuuruuurrrrurrdDDrdLuuuulllllllddddddrdDldRuuuluuruuurrrrurrdLLLLLulDrrrrrrddlUruLulllllldddrrrdLulldddrddddrrrrrrrruuullllllLrrrrrrrddlldlllllluuluurDDurrrrrrrrruuuuLrddddllulUUUUluRRurDrddddddlddlldlllluUddllluururRRRRRRllllldLrddrrrruUUUUUUUluRRulllllllldddrUluurrrrrrrrrrdddddddLLLLLLLLrrrrruuurDDldddrruuLrddlluUUUUUUddrdddrruuLrddlluluurDDldRuuuluuluullllllddrdrrdDDDrrrrdddlllluUluRRRRllldddrrrruuUUUrrruuuuulllllllldDllddddddddrrruuuuuuuLrddddrrdRullldddrrrruUUruulDrdLLLLrrrdddlllluuUUddddrrrUruulldRurDldRRdrUruuuuuuuuulllllllldddrdDDDrrrdddllluUluRRRRdrUruulDDDldRuulllluuuuluurDDDDDDrrrdddllluUluRRRRllluuurrdLulDDDrrrdddllluUUUUUUUdddddrUUruLdldddddllluuRRllddrrruUluRdddlUdlluurRdrU",
      "layout": [
        "#############",
        "#           #",
        "# +$. .$. . #",
        "# $$$#$$$#. #",
        "# .$ ..$ .  #",
        "# . .$ ..$. #",
        "# .#$$$#$$$ #",
        "#  . $.. $. #",
        "# .$.. $. . #",
        "# $$$#$$$#. #",
        "# .$ ..$ .  #",
        "#           #",
        "#############"
      ]
    },
    {
      "rank": 18,
      "sourceNumber": "starry-night-18",
      "name": "Rigel",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 1147,
      "solution": "ddrdrdrRdDlldlldddrrruurUUUUddlldlluRlddddrrruuruuuullulldRDDlddrUUUUUdddlddddrrruuruurRddrdrdrruuulluLLddLLrrrdrdrruLLdlUrruulullddlluuuulLulDDDldRuuurrrddddrruuuUddddlluuuulllddlddddrrrrUUUUddrruurrdrddlldlUUdrrruululluurrurrdLLDDlluuLLLLulDDDlddrUUUUluRdrrrrrddrruurruuuulllddlLLrrrururrddldldddlluulllllddlddddrUUUUUUdddddrrrRRllllluuuuurrrrrddrruurruuuulllddlDDuurururrdLLulDulDDurrrddldLLLLLrDDDDrdLdlluRRuuuuurrUUddllddddrrdLLLLrruuuuurruullDDDDDDrdLLdllluuruuuuluuuurrrrDDDDDDDDuuuuuuuullllddddrddlddddrrruRuuuuurrrrruuuulllDDDulluRRRRurDDulllllulllldRRRRRRRRurDllllldddddddrrdLuluuuuuuulllldddrddlddddrrrrUUUUUUUUruLLLrrrrrrrrdddllddlUrurruuulllllldddddddrrddrrrruuuuLdddldlluulluuuuuurrurrrrdddlDDDDrdLdlllullldllluuruuuuRRllddlddddrrrruuuuuUUUruLLrrrrrrrdddlldldRurDrddlUUUdddddllluulluuuuuurrurrrrdddLdlUrddddddlllullldllUUUUUdddddrrruuuuuuuuuullllddddRRRllluuuurrrrdddDDDDDrdLdllluuuuRRllddddrrruuuUUUUUddlllluuuurrrdRRRRRurrddddlldldlLrrrrddddllluulluUUUUUruLdddddddrrUdddrrruuuullLLLLLrruullldDDDuuuurDurrddlLulDDurrruurUUluRRRllldddddrUUUUddddrruLdlluuuuuRRddDDullddrRRRurDDDuuuulLLLulDDullddrRRRRRurDDullllluLLulDDrrrdRdrUluRRRurD",
      "layout": [
        "#############",
        "#@    #     #",
        "# *..$$$..* #",
        "# .#. $ .#. #",
        "# ..* $ *.. #",
        "# $  $ $  $ #",
        "##$$$ * $$$##",
        "# $  $ $  $ #",
        "# ..* $ *.. #",
        "# .#. $ .#. #",
        "# *..$$$..* #",
        "#     #     #",
        "#############"
      ]
    },
    {
      "rank": 19,
      "sourceNumber": "starry-night-19",
      "name": "Capella",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 767,
      "solution": "llllldRRurDDDrddlUUUUluRRRRurDDDDrdLuuuullldRRurDDDuullllddrddRRlluuluurrrrddrddDlddrUUUdldlLLdlUUUruulDulUUlldRurrddlUruLdlUrrrrrrddlUUluRurDDlllllddddDrddlUUUUUUluRdrUUruulldRurDldRRRRdrUrrdLLullllldlllddddRluuurrddDDrddlUUUlluuurrrurrruruurDldRllllldddrddrrDrdLuulluuUUluRRRdddrrUUddlluullllllddRRurDrddDlddrUUUUUUUruLulDDDllldddddRRurruuuuurrddrruurruuLLullddllldllluuRRurDDDrrrddrruurrddddddLLullulluuuurruuLLulDDrrrddLulDDDDDllddrrUUUUUUUruulldRdrrddLulDDDDllddrrUUUUUUUUdrruulLulDrrrurrdrrddddLLrrddddllullulldllulldRRRlddrruUUUUUUUdrruulLulldRRRlddddddrrdrrdrruuuuuuuullullDurrdrrdddddddLLddlluuLulDllddrrUUUUUUUUdddddrrdddrrurruuuuuuuullulldlLrrurrdrrddllddLLrruurDrdLLrruuuullulldllddrrddLulDDDDllddrrUUUUUUUddddrrdddrruuuLLLdlUrrrrdrruLLdddlluLulllddrrUruL",
      "layout": [
        "#############",
        "# #   #   # #",
        "# $ . $ . $ #",
        "# ....+.... #",
        "# $ . $ . $ #",
        "# $$.$$$.$$ #",
        "# $ . $ . $ #",
        "# #...#...# #",
        "# $ . $ . $ #",
        "# $$.$$$.$$ #",
        "# $ . $ . $ #",
        "# #   #   # #",
        "#############"
      ]
    },
    {
      "rank": 20,
      "sourceNumber": "starry-night-20",
      "name": "Vega",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 812,
      "solution": "lllllddRluurrrrrrrrrrddLruullllllllllddddddddRlddrrrrrrrrUdrruuuuuuuuuullllllldRdddRRRllluuuulllldddddrDrrrRRRlllllluluuuuurrrrddRldRuluulllldddddrdrrrUUruulDrdLLDrdLLrruuuuuulllldddddrUluuuurrrrddddlLrruuuurrrrrrdddddlUruuuullllllddrddrrRllluuluullllddddddddddrrruRldllluuuuuuRluuuurrrrrrrrrrddddLLLLLLddrrrUdllluurrRRllluuluurDDDldddrrruulLrrddllluUUruuulllllddrDuluurrrrrddddrrddldLuluuruuuulllllddddddddddrrrruuUUUdrrruulDuluuuullllldddddrUluuuurrrrrrrrrrddddLLLrrdLulDrrruuuuullllldddlDDDuuruuuurrrrrddlDrdLLrruuuullllllllllddddrdRRdrUlllldddddrrrrrrrrrruuulUrddddlllllllllluuuuurrrrdrdrdLuululllldddddrrrrrrrrrruLLrruuuuuuuuulllllldDruurrdLrurrDDuLrrddddddddlUdldlllllllluuuuRRRlllddrUluRRululuurDDuuluurDDuRlldddddddddrUUdRluluuuuuurururrrrdLulDullllddddrDldRlddrdrdrrrrrrrruuuulUruLrddddldldllUUddlluRdrU",
      "layout": [
        "#############",
        "#     @     #",
        "# $$.$ $.$$ #",
        "# $.#.$.#.$ #",
        "# .##.$.##. #",
        "# $...$...$ #",
        "#  $$$#$$$  #",
        "# $...$...$ #",
        "# .##.$.##. #",
        "# $.#.$.#.$ #",
        "# $$.$ $.$$ #",
        "#           #",
        "#############"
      ]
    },
    {
      "rank": 21,
      "sourceNumber": "starry-night-21",
      "name": "Arcturus",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 1334,
      "solution": "rrrrrdrddddddLLrruuuuuululllllllllldddrRRRurrdLLLLrrrrrRlllddLLrrRRdrrdrdddddlllllllllluuurRRRdrruLLLLrrrrrRllluuLLrrddrrUUddlluuluurrdRulluurrrRDDuullllddlddrddlllLrrrruuluuruurrrrdrrdddldddddlllllllllluuUrrrrruuRlddrruUlllullldDuurrruruurrrrdrrdddldddddlllllllllluuuRRRRdrUrruuluurUdlllldlldddldddrrrrrrrrrruruuuuuuullulLLulDrrrrdrrdddlddLLLuulllullldddlluuuuuruRRRDDuullllddddddrruuurRdrUluRluullluuurrrrrrDDldRRRlddlddlluuluuluRRRllldlluuurrrrrrdDllldddrddrruuruuLuuullDurrddlLrrdrddlddllullluRlddddlluuuuururrrdDrdLLulDDDuurruuullllddddddrRRRRllluuurrrdrruuruuruLdlUlluurrDDuulllllldlddddRRRlluurrrdDrdLullddddldddrrrrUUddrrrrrruruuuuuuuuulDLLrrrddddlddllluuluuruUruLLrrRlldddlddlluuluuluLdlluurDDlddrrddddrdLullddrUluRdddrrrrrrrrrruuuuulUUUdddrddlUUddlluullluuluullDDrrrddrrrddrdRurrddlUruLdddlllllluurrRRRlllllddrrrrrruUUdddllllUdlluurRRRRlllllddlllluurrRRlllluluuuuuuruuurrrrddLLLdlluurDldRlddddddrdrrruUUUUUUlulluurrrrddLLLrrdddrddrruuLLrrruuuluullddlddDDDDDldllddrrrruuLLLrrrddrrrrrruruuuullUULLLLLdlUUUddrrrruuuluullddLLrdddrrrrrrddrrddlUruLdlUrrddddlUUdllllddlluuRRRRRlllddrrrruruuuuuuLLLLLLLrrruuuluullddlddDDDDDldRRluuuuulllluurRRurDDullddrRRluulllluurDldRuuurrrrddllLrrdddrddrruuLLrrruuuluullddlddDrrrrrrrruulLLulDDurrrrddlllLLrrrUdlllddlllddlLrruuruuRRRlllddlddlluuUdddrrdrddlllluluuuuuurRllddRlddddrdrrrruululluUllddR",
      "layout": [
        " #############",
        "##     @     ##",
        "#  ###$#$###  #",
        "# .$ $ . $ $. #",
        "#  .$ ... $.  #",
        "# .$#$#.#$#$. #",
        "# $ . $ $ . $ #",
        "# #... # ...# #",
        "# $ . $ $ . $ #",
        "# .$#$#.#$#$. #",
        "#  .$ ... $.  #",
        "# .$ $ . $ $. #",
        "#  ###$#$###  #",
        "##           ##",
        " #############"
      ]
    },
    {
      "rank": 22,
      "sourceNumber": "starry-night-22",
      "name": "Alpha Centauri",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 1783,
      "solution": "llllddRRRuulllllddddrrddrrrruuuUUluRRRRRllluuluullDDDrdddllluurRRdrUUUUUdddldddllUdrruulLLrrrruuuurrRRuulDrdLuulllllllddDDDDrddlUUUUUUlldRurDlldddddddrrddrrrruuuuurrurrddDDrruLdlUrdddllllluullLLddrUluRldlluuuuuuuurrRlllddddddddrrrdrrruuuuuuuuuullDDDrdddlluuRRurDDDDDuuuuuuuurDDDlddrruLdlUlllluRdrrrrrrrdLLLLdlUruLLrrrrrruuLLrrddllluUluurDDDurrrddlldlluRRRdrUllllddddrrUUddlluuururrdLLullddrdRdrUUdlluluurruuuulllLLdlUrrrrrrddddlllUUUddrdrruuuullLLLrrdddllddrUluRdrUUUddrdrruuuullLdddldddDDlddrUUUdldlluuuuuuuurrrrurrrddrrrUUluRdddllluuRRllddrrruUddlUruLddllddlllllddDDrdLuuuururrddrUruLLLLulDDDDDrddrrrrrrrruuulLLLdlUUUruLLLLulDDDururrrddddlUUUrruuuuullldddlldddRRRurDDldRuuuuLLulDDldRRRurDuruuuuRRlldddlluRdrUUluRlddllldddddddrrrrrrrruuullldRRurrddldlllllllluuuurrrururrdDDuuulldRurDlddrrrDullldRRulluurDDuuulluurrDDrdLulDrddllLdlUruLuullddddddrrrUUUUluRRRurDlllddrrrrrruuuLLLLdlUUluRldldddddLrrddllluUUdrrruuuuuuuLulDrrddddddrrdLulDuuurrruuurDldllldddrrrrrruuulLLLLulDDDldRRluuuuuulllllldddRRRRRdrUUUruLLrddlllldlluuurrDDrdLrrrrrrruuuuuulllDDDDDldRRRdrUUdlluuuuluurrrddLLdlUrddddrrrrrdddllUUluRlllllddddlluUUluRRRRRuuuurrdDDDrdLLLLdlUruLullluurRRurDrddddrrrddlLLdlUrrrruuuuuluurDDDlddlllldddlllUUUruuluuuRRRllldddrddddRdrUUUUdddlluuuurRRlllluurrrrrdDDuuuurrdddddlLrrrddlUruLLruuuuulldllllDDDDDldRRdrUUUddlluuuurrrruuRurDDDDDDrdLLLLdlUUdrrrrrdLLLulllluuuuuulllddddddRRRRRRRRdrUUUUUUruLLulDDDuurrddddrddrruuuuuuLLLLulDDulllldddddddddrrrrrrUUUUUUUUruLLLrruuurDDldddddrddrruuuuuulLulDDDDDDrdLLLrruuuuuuuuullllllDDDDldRRRlluullluRRdrdddddddddrrrrrruuuuuuuuuuuulllllldDDDldRRluuuuurrrrrrrdddrruLLdlUUruLLLrrddddddddddddlllllllUUruuuuuuulllddddddrRdrUUUUUUluurrdLLLulDDDuurrruuulDDldRurDDDDDlddrUUdddddrrrrrrrUUluuuuuruurrddddddlLdlUUUrddrrdLLdlUluRRRdrUUUddllldddlllllluuullldRRurDDldRRR",
      "layout": [
        " #############",
        "##     .     ##",
        "# . $##.##$ . #",
        "#   $  .  $   #",
        "# $$$$$.$$$$$ #",
        "# # $.#. .$ # #",
        "# # $ ...#$ # #",
        "#......@......#",
        "# # $#... $ # #",
        "# # $. .#.$ # #",
        "# $$$$$.$$$$$ #",
        "#   $  .  $   #",
        "# . $##.##$ . #",
        "##     .     ##",
        " #############"
      ]
    },
    {
      "rank": 23,
      "sourceNumber": "starry-night-23",
      "name": "Canopus",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 1504,
      "solution": "lddrrdddrrdLuluuulluururrddrrrrrruurrdrddllddddddrrddldlluullllllddlluluurruUruLdlUrdddllddrdrruurrruuuLrdddlluRdrUdrrrddrruruulluuulldLrurrdddrrddldlluullllllddlluluurruururrdLLuluuulluururrddrrrrrruurrdrddllddddddrrddldlluullllllddlluluurruUluRRRlldddRdrrrrrrddrruruulluuLrddrrddldlluuluRldlluRlldlluluuuuuulluururrddrrrrrruurrdrddlldddlluRRuurruulullddllldddRluuullluulldlddrrdddrruRlddrDDuulllddrdrRurDDuuluululluuulluururrddrdRurDullluulldlddrrRurrrrrdLruruurrdrddllLrddldlluUUUdddddDDlddrUUUUdddrruUUruLddddlllllluRlluurrrdDldRurDuluuluuLrddrddrrdrruuruuuuululllllldldDDDDurrrddlldddlluluurRRRRuululllluRdrrrdrdddrrrruuruuuuululllllldldDldRRuluurDDDldddrrruulLrrddllluUruLLrruuuurrruurDlldlldddddrrdddrrrruuruuuuululLLLLrrrrrdrddldddddlllluuulluuuullluururrdDDDDDldddrrruulLrrddllluUruLruuuurrdLulDDDDldddrrruulLrrddllluUrrrdddrrrruururruuLdllddddlllluuulluuuurrurrrrdrdDldRRuluululldddRRlluuurrdrdDldRuuululllldRurrrdrddllluUddrrruululLdlUUrdrrdLrrddllluUruLdlUrdddrrdddddddrruruulLrrddldlluuUUUUruuulllddrRdrUUdllluurruuurrdrddlLLLrrddllluUruLrrdDullddrRurDuulllllllddddDldRRluurrdDldRuuulluurrUdlluurRRRurrdLLLLLulDDDDDDldRRluurrdDuulluurruurrrrdddddddlluuuRldddrruuUUUruulDullddrRuuuuurrdLulDDDDDDDrddlUddlluuurRllddRdrUUUUUUruLLLLLLulDDDDDlddrUdrruulLdddddlluRdrUUUUUUUluurDurrddlLrruurrrrdddddrdrrddlUruLLrdddlluuUUUUUUruLLrddlluUlllldddddldlDldRRdrUUUUUUUUluRRlddrruUrrrrrrUruLLulDDDDDDDDrdLLruulldDrruuuuuullllluluulldDldRRluuurrddDDDuuuuLulDDldRRRRRRRddrruuLLrrdddddrdrddLdlUUUUUUUlluurrDD",
      "layout": [
        " #############",
        "##   # . #   ##",
        "# @$ # . # $  #",
        "# $#  ...  #$ #",
        "#   $ $.$ $   #",
        "### $#$.$#$ ###",
        "#  .$ $.$ $.  #",
        "#......#......#",
        "#  .$ $.$ $.  #",
        "### $#$.$#$ ###",
        "#   $ $.$ $   #",
        "# $#  ...  #$ #",
        "#  $ # . # $  #",
        "##   # . #   ##",
        " #############"
      ]
    },
    {
      "rank": 24,
      "sourceNumber": "starry-night-24",
      "name": "Sirius",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 679,
      "solution": "rruuuuuuuulluullllDDDDrdLulDDDldRuuuruuuuullllddllddddRRRRurDldRuuruuuuurrrrddrrddddLLLLulDuuuluuulldRurDDDDrdLulDDuruuuuurrdLulDDDDldRurDlllldllluurDldRRRdrUluRRurrrrddrrruulDrdLLLdlUruLulllllddlllddrUluRRRdrUluRurrrrrddrrrddlUruLLLulDDuuuulluuulllldRRRurDDDrdLLulDDldRuurruuurrurrdLLLulDDDldRRurDDuulluulllldlluRRRRRurDDullllldDDDldRRRdrUUluRRRRllllddlllddddrUUUluRRRurDDulllddddrddrrrrUUddrrrruurruuuuuuuuuLLLLLulDrrrrrrdddlUUruLLLLLLLLLLulDDDDDldRRRdrUUluRRllddllddddrddrrrrrrrruurUUUUUUUUruLLLLLLLLLLulDDDDDldRRRdrUUldllddddrddlUUUUUluRRRllddddrddrruLLdlUUUUUluRRlddddrdrrdrruLLLLdlUUUUUluRddddrdrrrrdrruLdlUrrdrruLLLLLLLLdlUUUUUUUUUUluRRRRRRRRRRurDDDDDrdLLrddddlddrUUUUUruL",
      "layout": [
        " #############",
        "##           ##",
        "# $ $ $$$ $ $ #",
        "#   ###.###   #",
        "# $##  .  ##$ #",
        "#  # . . . #  #",
        "# $#  ...  #$ #",
        "# $....#....$ #",
        "# $#  ...  #$ #",
        "#  # . . . #  #",
        "# $##  .  ##$ #",
        "#   ###.###@  #",
        "# $ $ $$$ $ $ #",
        "##           ##",
        " #############"
      ]
    },
    {
      "rank": 25,
      "sourceNumber": "starry-night-25",
      "name": "Stars-Final",
      "author": "Sam Cornwell",
      "tier": "STARRY NIGHT",
      "minimum": null,
      "pushMinimum": null,
      "solutionMoves": 26020,
      "solution": "llddddddddddddddddddddddddddddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrruuuuuuuuuuuuuuuuuuuuuuuuuuuullllllllllllllllllllllllllllllllllllllllllddddddddddddddddddddddddddrrrruuuRluRluRluRluRluRluRluRluRluRluRluRluRluRluRluRluRluRluRluRluurDurrDLrurDDrrDDrrDDDDDDDDDDDuuuuuuuuuuullLrDLrDLrDLrDLrDLrDLrDLrDLrDLrDLrDLrDLrDLuuuuuuuuuuuuruuullullulllldddRRlldRRlldRRlldRRlldRRlldRRlldRRlldRRlldRRlldRRlldRRllddRRlluRRllddRRlldRRlldRRlldRRlldRRlldRRdddrrrrlllluuRRRRRlUUUdddrRRRRRRRRRRRRRRRRRRRRRRRRllllllllllllllllllllllllllrrUdrUdrUllldlllluuuuuuuuuuuuuuuuuuuuuurrrrddrrddrrdddddrrrrrddDldRRluuuuurrrrdLulDDurrrrrddddlUruLLrddlldddlluRdrUUdllululuuuullllluuurrrrrrrDDrdLulDDuuruurDlddrruLulDrdLLulDDDDldRuuuuurruurrDDldRRurDDDDrdLuuuuulluurDDldRurDDDDDrdLLruuuuuuluurDDDDDDDDrdLLLLdlUrrruruuuuuuuurDlddrruLulDDDDDDDrdLLLLLdlUrrrruruuuuuuuurrDlddrruLLulDDDDDDrdLuuuuuuuurrrDlddrruLLLulDDDDDDDrdLLLLLrrrruuuuuuuuurrrrDlddrruLLLLulDDDDDDDrdLLLLrrruuuuuuuuurrrrrrrddLLLLLLulDDDDDDDrdLLLrruuuuuuuuurrrrrDurrddlLLLLLulDDDDDDDrdLLruuuuuuurrrrrrruLLLLLLulDDDDDDDDrdLuuuuuuurrrrrrrddddddddddlllllllllllllllllUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUUruLdddrUUUruLLrddddrUUUUruLLLrrdddddrUUUUUruLLLLrrrddddddrUUUUUUUUUluurrdLLLLLLulDDDrrrrrrddddddddrruLLdlUUUUUUruLLLLrrrrddddddrruLLdlUUUUUUUruLLLLLLLLLLulDDDDDDuuuuuurrrrrrrrrrrrrdddddddLLdlUUUUUUruLLLLLLLLLLulDDDDDuuuuurrrrrrrrrrrrrddddddLLdlUUUUUruLLLLLLLLLLulDDDDuuuurrrrrrrrrrrrrdddddLLdlUUUUruLLLLLLLLLLulDDDuuurrrrrrrrrrrrrddddLLdlUUUruLLLLLLLLLLulDDuurrrrrrrrrrrrrdddLLdlUUruLLLLLLLLulDurrrrrrrrrrrddLLdlUruLLLLLLLLLulDurrrrrrrrrrrrdLLLLLLLLLLLLulDrrrrrrrddddddddlllllllllUdrrrrrrrrruuuuuuuullllllllllddddddRddlUUluRRldddlUUUluRRRuuuullluuuuulldddddddddddRRRRurDllllluRRRurDDulllluRRRRurDDullllluRRRRurDDullllluRRRRurDDullllluRRRRRurDDulllllluRRRRurDDDuullllluRluuuurrdddDldRRRRurDDullllulluRluuurrddDDldRRRurDDuulLdlluurDldRRRRurDulllluurDldRRRRRRRRurDDuuulllllllDldRRRRRRRRurDDuuulllllllDldRRRRRRRRurDDuuulllllllDlddrruLulDDuuurrDurrddlLLLulDDDDDDDuuuuuurrrrruLLLLulDDDDDDDuuuuuuulluulluulluullllddddddddddddddddddddddrrrrrrrrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUdrUlllllllllllllllllllllllldlllluuuuuuuuuuuuuuuuuuuuuurrrrddrrddrrrrrrrrrrrrrrrrrDDrdLLLLLLLLLLLLLLulDDDDDDDDDDDrdLLruuuuuuuuuuuuluurrrrrrrrrrrrrrDDrdLLLLLLLLLLLLLulDDDDDDDDDDDrdLuuuuuuuuuuuurrrrrrrrrrrrruurrDlddrruLLulDrdLLLLLLLLLLLLLulDDDDDDDDDDDuuuuuuuuuuurrrrrrrrrrrrruurrrDlddrruLLLulDrdLLulDDDDDDDDDDDrdLLLLLLLLLLurrrrrrrrruuuuuuuuuuurruullDDDDDDDDDDDDrdLLLLLLLLLLLrrrrrrrrrruuuuuuuuuuurruLulDDDDDDDDDDDDrdLLLLLLLLLLrrrrrrrrruuuuuuuuuuuuulDrddlluRurDDDDDDDDDDDrdLLLLLLLLLrrrrrrrruuuuuuuuuuuuullDrddlluRRurDDDDDDDDDDDDrdLLLLLLLLLurrrrrrrruuuuuuuuuuuuulllDrddlluRRRurDDDDDDDDDDDrdLLLLLLLLrrrrrrruuuuuuuuuuuuullllDrddlluRRRRurDDDDDDDDDDDDrdLLLLLLLLurrrrrrruuuuuuuuuuuuulllllDrddlluRRRRRurDDDDDDDDDDDrdLLLLLLLrrrrrruuuuuuuuuuuuurrrrrrrrddddddddddddddLLLLLLLLLLLLLLrrrrrrrrrrrrrruLLLLLLLLLLLLLrrrrrrrrrrrrruLLLLLLLulDDrdLLLLLLurrrrruuuuuuuuuuuuulllllllllllllluurrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddLLLLLLLLLLLLLLrrrrrrrrrrrrrruLLLLLLLLLLLLLLrrrrrrrrrrrrrruLLLLLLLLLulDDrdLLLLurrrurrrrrrrruLLLLLLLulDDrdLLLLrrrurrrrrrrrrruLLLLLLLLLulDDDrdLLLurruurrrrrrrrrruLdllluuuuuuuuuluurrrdddddddddDrdLLLLLLLLulDDDrdLLuruurrrrrrrruLLLLLLLulDDDrdLLLrruuurrrrrrrruuLLLLLLLulDDDDDrdLLrrrrrrrrrrrddddLLLLLLLLLLLLLLLLLLLLLLLLLdlUUdrrrrrrrrrrrrrrrrrrrrrrrrUUddrruuulLLLLLLLLLrrrrrrrrrrdLrddlluUUruLLLLLLLLLrrrrrrrrddddrUUruLLLLLLLLLuuuurrrrrrruLLLLLLulDDDDDuuurrrrrrrrruLLLLLLLLLulDDDDuuuurrrrrrrruLLLLLulDDDDDDDuuuuuurrrrrruLLLLLLulDDDDDDDuuuuuurrrrrrruLLLLLLLulDDDDDDDuuuuuurrrrrrrruLLLLLLLulDDDDDDDuuuuuurrrrrrrruLLLLLLLulDDDDDDDuuuuuurrrrrrrruLLLLLLLulDDDDDDDuuuuuuuurrrrrrDurrddlLLLLLLulDDDDDDuuuuurrrrrrrruLLLLLLLulDDDDDDrrrrrrrrdddrruLLdlUUruLLLLLLLrrrrrrrddrruLLLLLLLLulDDDDDuuuurrrrrrrrruLLLLLLLLulDDDDDuuuurrrrrrrrruLLLLLLLLulDDDDDuuuurrrrrrrrruLLLLLLLLulDDDDDuuuurrrrrrrrruLLLLLLLLulDDDDDuuuurrrrrrrrruLLLLLLLLulDDDDDuuuurrrrrrrrruLLLLLLLLulDDDDDrrrrrrrddddddddddddlllllllllllllllllllllllldllllulldRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRllllllllllllllllllllllllllllddlUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRlllllllllllllllllllllllllllddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrruuuLLLLLLLLLLLLLLLLLLLLLLLLLLLdlUdllllddrrrrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUddrUUlllllllllllllllllllllllddlllUdrUdrUrrrrrrrrrrrrrrrrrrrrrrrrdrrrrruuuuLLLrrruLLLrrruLLulDDDrdLuuurrruLLulDDDDuuurrruLLulDDDDuuurrruLLulDDDDuuurrruLLLLLLLLulDDDDuuurrrrrrrrruLLLLLLLulDDDDDuuuurrrrrrrruLdlluurDDDDDDDDDuuuuuuuurruLdlluurDldRurDDDDDDDDDuuuuuuuuuruLLLLLLLLLulDDDDDDDuuuuuurrrrrrrrrruLLLLLLLLLulDDDDDDDuuuuuurrrrrrrrrruLLLLLLLLLulDDDDDDDuuuuuurrrrrrrrrruLLLLLLLLLulDDDDDDDuuuuuurrrrrrrrrruLLLLLLLLLulDDDDDDDuuuuuurrrrrrrrrruLLLLLLLLLulDDDDDDDuuuuuurrrrrrrrrruLdlllulllllllllllllllllllllluurrrrrrrrrrrrrrrrrrrrrrrrdDrdLLLLLLLLulDDDDDDuuuuurrrrrrrruuullllllllDDDDDDDuulllllllllllllllluuRurDDullddrRurDDDDDDDDDuuuuuuuuulLLulDDDDDDDDDDDuuuuuuuuuuuurrrrDlddrruLLLulDDDDDDDDDDDuuuuuuuuuuuurrrrDlddrruLLLLLulDDDDDDDDDDuuuuuuuuuuurrrrrrDlddrruLLLLLulDDDDDDDDDDuuuuuuuuuuurrrrrrDlddrruLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrDurrddlLLLLLLLulDDDDDDDDDuuuuuuuurrrrrrrrruLLLLLLLulDDDDDDDDDDuuuuuuuuuuluurDDldRurDDDDDDDDDDuuuuuuuuuuluurDDldRurDDDDDDDDDDuuuuuuuuuuluurDlddrruLLLulDDDDDDDDDDrdLuuuuuuuuuuuurrrrDlddrruLLLLulDDDDDDDDDDuuuuuuuuuuulDDDDDDDDDDuuuuuuuuuurrrrrrDlddrruLLulDDDDDDDDDDuuuuuuuuuuurrrDlddrruLLLLulDDDDDDDDDDuuuuuuuuuuurrrrrDlddrruLLLLLLulDDDDDDDDDDuuuuuuuuuuurrrrrrrDlddrruLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrDlddrruLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrDlddrruLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrDlddrruLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrDlddrruLLLLLLLLulDDDDDDDDDuuuuuuuuuulllllluurDDDDDDDDDDDuuuuuuuuuuurDDDDDDDDDDDuuuuuuuuuuurDDDDDDDDDDDuuuuuuuuuuurDDDDDDDDDDDuuuuuuuuuuurDDDDDDDDDDDuuuuuuuuuuurDDDDDDDDDDDuuuuuuuuuuurDDDDDDDDuuuuuuuurDDDDDDDDuuuuuuuurDDDDDDDDuuuuuuuurDDDDDDDDuuuuuuuurDDDDDDDuuuuuuurDDDDDDDDulDuuuuuuuurrDDDDDDDDuuuuuuuurDDDDDDDDuuuuuurDDDDDDuuuuuurDDDDDDuuuuuurDDDDDDuuuuuurrDDDDDDrdLuuuuuuurDDldRurDDDDDDDDDDDDDuuuuuuuuuuuuuluurDDldRurDDDDDDDDDDDDDuuuuuuuuuuuuuluurDDldRurDDDDDDDDDDDDDuuuuuuuuuuuuuluurDDldRurDDDDDDDDDDDDDuuuuuuuuuuuuuluurDDDldRurDDDDDDDDDDDDuuuuuuuuuuuuluRluurrdDDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuuLLLLLLulDDDDDDDDDDDDDDuuuuuuuuuuuuuullllluurDlddrruLLLLLLLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLulDDDDDDDDuuuuuuuuurrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLLulDDDDDDDuuuuuuuurrrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLulDDDDDDDDDuuuuuuuuuurrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLLulDDDDDDDDuuuuuuuuurrrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLLLLulDDDDDDDDuuuuuuuuurrrrrrrrrrrrrrrrrrrrDlddrruLLLLLLLLLLLLLLLLLLLLLulDDDDDDDDuuuuuuuuurrrrrrrrrrrrrrrrrrrrrrDDDlddrruLLLLLLLLLLLLLLLLLLLLLLLulDDDDDDuuuuurrrrrrrrrrrrrrrrrrrrrrrrruuLLLLLLLLLLLLLLLLLLLLLLLLLulDDDDDDDDuuuuurrrrrrrrrrrrrrrrrrrrrrrrrruLLLLLLLLLLLLLLLLLLLLLulDDDDDDuuuuuurrrrrrrrrrrrrrrrrrrrrruLLLLLLLLLLLLLLLLLLLLLLulDDDDDDDDuuuuuuuullllllllldRRRRurDDDDDDDuuuuuuullllllldRRRRRRRurDDDDDDDDuuuuuuullllllddlUluRRRRRRRRurDDDDDDDDuuuuuuullllllllldddddddddddddddddddddddlluRRRRRRRdrUlllllllluRRRurDldRRRRRdrUlllllulllluuuuuuuuuuuuuuuuuuuuuuuurrrrrrrrDDDuuurDDDDDDDDuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDDuuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuuurDDDDDDDDDDDDDDDDrdLuuuuuuuuuuuuuuuuurDDDDDDDDDDDDDDDDDDrdLuuuuuuuuuuuuuuuuuuurDlddrruLLLulDDDDDDDDDDDDDDuuuuuuuuuuuuuuurrrrDlddrruLLLLulDDDDDDDDDDDDDuuuuuuuuuuuuuurrrrrDlddrruLLLLLulDDDDDDDDuuuuuuuuurrrrrrDlddrruLLLLLulDDDDDDDDDrdLuuuuuuuuuuurrrrrrDlddrruLLLLLLulDDDDDDDDDDrdLuuuuuuuuuurrrrrrrrrrdLLLLLLLLLulDDDDDDDDDDrdLuuuuuuuuuurrrrrrrrrrdLLLLLLLLLulDDDDDDDDDDrdLrrrrrrrrddddddddddddrruuuuuuuuLLLLLLLLLrrrrrrrrrddddLLrruLLLrrruLLLrrruLLLLLLLLurrrrrrrruLLulDDDDuuurrruLLulDDDDuuurrruLLLLLLLLLulDDurrrrrrrrrruLLLLLLLLLulDDurrrrrrrrrruLLLLLLLLLulDDurrrrrrrrrruLLLLLLLLLulDrrrrrrrrrruLLLLLLLLulDDDrdLuuurrrrrrrrruLLLLLLLLLulDDurrrrrrrrrruLLLLLLLLLulDDurrrrrrrrrruLLLLLLLLLulDDurrrrrrrrrruLLLLLLLLulDDDDDDDDDDDuuuuuuuuuurrrrrrrrruLLLLLLLLulDDDDDDDDDDDuuuuuuuuuurrrrrrrrruLLLLLLLLulDDDDDDDDDDDrrrrrrrrrddddddddLrdddlluuUUUUUUUUruLLLLLLLrrrrrrrrdddddddddLrddlluUUUUUUUUUUruLLLLLLLrrrrrrddddddddddddrUUUUUUUUUUUUruLLLLLLLLuuuuuuuuuuurrrrrrrrrrddddddddddLLLLLLLLLLrrrrrrrrrruLLLLLLLLLLrrrrrrrrrruLLLLLLLLLLrrrrrrrrrrdddddddddLLLLLLLLLrrrrrrrrruLLLLLLLLLrrrrrrrrruLLLLLLLLLrrrrrrrrruLLLLLLLLLrrrrrrrrruLLLLLLLLLrrrrrrrrruLLLLLLLLLuuuurrrrrrrrruLLLLLLLLLulDDDDuuurrrrrrrrrruLLLLLLLLLulDDDDrrrrrrrrdddrUUruLLLLLLLLLuuurrrrrrrrruLLLLLLLLLulDDDuurrrrrrrrrruLLLLLLLLLLLLLLLLLLLLLLLLLLLulDDDDrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddLullddrUruLLLLLLLrrrrrrrrddLullddrUUruLLLLLLrrrrrrrdddLullddrUUUruLLLLLrrrrrrddddLullddrUUUUruLLLLrrrrrdddddLullddrUUUUUruLLLrrdddddddrUUUUUUUruLLLLLLLLuuuuuuuuuuuurrrrrrrruLLLLLLLulDDDDDDDDDDDDDuuuuuuuuuuuurrrrrrrruLLLLLLulDDDDDDDDDDDDDDuuuuuuuuuuuuurrrrrrruLLLLLulDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuuurDDDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuuurDlddrruLLLLLulDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuurrrrrrDlddrruLLLLLulDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuurrrrrrDlddrruLLLLLulDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuurrrrrrDlddrruLLLLLulDDDDDDDDDDDDDDDuuuuuuuuuuuuuuuurrrrrrrrddddddddddddddddLLLLLLulDrrrrrrruLLLLLLLLLLulDrrrrrrrrrrruLLLLLLLLLulDDurrrrrrrrrruLLLLLLLLulDDDuurrrrrrrrruLLLLLLLulDDDDuuurrrrrrrruLLLLLLulDDDDDuuuurrrrrrruLLLLLLLLLLulDDDDDuuuurrrrrrrrrrruLLLLLLLLLulDDDDDDuuuuurrrrrrrrrruLLLLLLLLulDDDDDDDuuuuuurrrrrrrrruLLLLLLLulDDDDDDDDuuuuuuurrrrrrrruLLLLLLulDDDDDDDDDuuuuuuuurrrrrrruLLLLLLLLLLulDDDDDDDDDuuuuuuuurrrrrrrrrrruLLLLLLLLLulDDDDDDDDDDuuuuuuuuurrrrrrrrrruLLLLLLLLulDDDDDDDDDDDuuuuuuuuuurrrrrrrrruLLLLLLLulDDDDDDDDDDDDuuuuuuuuuuuuurrrrrrDurrddlLLLLLulDDDDDDDDDDDDuuuuuuuuuuurrrrrrruLLLLLLLLLLulDDDDDDDDDDDDrrrrrrrrrrrddddddddddddddddlllllllllllUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlUUUdddlllllUUddrUUddrUUddrUUddrUUllllddllUdrruululldRRRRRRRdrUlllllddlUluRRRRRRRdrUllllllllddllUdrruuullldRRRRRRRRRRRdrUlllllllllddlUluRRRRRRRRRRRdrUrrrrrrrrrrrrrrrrrrddrrUdrrrrrrrrruuuuuuuuuuuullllllddddddddddllLLrddlluUddrUruLLdlUrrrddrrrrrrrrruuLLLLLLLLLLLLdlUrrrrddrUdrrrrrrrruulllllllLLLLLLdlUrrrrrrddrrrrrrrUruLLLLLLLLLLLLLLdlUrrrrrrrddrrrrrrUruLLLLLLLLLLLLLLdlUrrrrrrrrddrUdrrrrruullllLLLLLLLLLLdlUrrrrrrrrrrddrUdrrrruulllLLLLLLLLLLLLdlUrrrrrrrrrrrrddrUluurrdLLLLLLLLLLLLLLdlUrrrrrrrrrrrrrrddrUluurrdLLLLLLLLLLLLLLLLdlUrrrrrrrrrrrrrrrrddrUruLLLLLLLLLLLLLLLLLLdlUrrrrrrrrrrrrrrrrrrrrruLLLLLulDrdLLLLLLLLLLLLLLLLdlUrrrrrrrrrrrrrrrrurrrrrruLLLLLulDDrdLLLLLLLLLLLLLLLLLdlUrrrrrrrrrrrrrrrrruurrrrrruLLLLLulDDDrdLLLLLLLLLLLLLLLLLLdlUrrrrrrrrrrrrrrrrrruuurrrrrruLLLLLulDDDDrdLLLLLLLLLLLLLLLLLLLdlUllllllllllllllllddllluuRRRRRRRRRRRRRRRdrUlllllllllllllddlUdlluurRRRRRRRRRRRRRRRdrUlllllllllllllllddlUluRRRRRRRRRRRRRRRRRdrUrrrrrrrrrrrrrrrrrrrruuuurrrrrruuuuuLullddrUUUUruLLLLLLLLrrrrrrrrrdddddLullddrUUUUUruLLLLLLrrrrrrrddddddLullddrUUUUUUruLLLLLrrrrrrddddddddLdlUUUUUUUUUruLLLLLLLulDuuuuuuuuuuuullllllllllllllllllllllllllDrddlluRRRurDDDDDDDuuuuuuuulllllDurrddldlluRRRRurDDDDDDuuuuuuulllllllllddRRRRRRRRRRurDDDDDDDuuuuuuuullllllllllDldRRRRRRRRRRRurDDDDDDDuuuuuuuullllllllllDldRRRRRRRRRRRurDDDDDDDuuuuuuuullllllllllDldRRRRRRRRRRRurDDDDDDDuuuuuullllllllllluRurDldRRRRRRRRRRurDDDDDDDuuuuuulllllllllluRRRRRRRRRRurDDDDDDDDuuuuuulllllllllllllllldRRRRRRRRurDDDDuuullllllllldRurrddlUluRRRRRRRurDDDuullllllllldddRluurrrdddlUUUluRRRRRRRurDDullllllllldddddRluurrrdddlUUUUUluRRRRRRRurDllllllldddlUUluRRRRRRRRRurDDDDDuuuulllllllldddddlUUUUluRRRRRRRRRurDDDDuuullllllllllddddddRurrddlUUUUUUluRRRRRRRRRurDDDDDuuuullllllllllldddddddRurrddlUUUUUUUluRRRRRRRRRRurDDDDDuuuullllllllllllddddddddRurrddlUUUUUUUUluRRRRRRRRRRRurDDDDDuuuullllllllllllldddddddddRurrddlUUUUUUUUUluRRRRRRRRRRRRurDDDDDuuuullllllllllllllddddddddddRurrddlUUUUUUUUUUluRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllldddddddddddRurrddlUUUUUUUUUUUluRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllddddddddddddRurrddlUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllldddddddddddddRurrddlUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllllddddddddddddddRurrddlUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllllldddddddddddddddRurrddlUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllllllddddddddddddddddRurrddlUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllllllldddddddddddddddddRurrddlUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllllllllddddddddddddddddddRurrddlUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRurDDDDDDrrrrrrrrrrrrrrrdddddddddddddrUUUUUUUUruLLLLLLLLLLrrrrddddddddddddddlllllllllllllllllllllllllllllllluulllluuRurrddlUUUUUUUUUUUUUUUUUUUluRRRlldddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUluRRRRRurDllllllddddddddddddddddddddddddlluuuuuuuuuuuuuuuuuuuuuuuuuuuurrrrrrrrrrrrDDDDDDDuuuuuuurDDDDDDDDuuuuuuuurDDDDDDDDuuuuuuuurDDDDDDDDuuuuuuuurDDDDDDDDuuuuuuuulllllllDDDDuuuurDDDDuuuurDDDDuuuurrrrrrDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDuuuuuuuuurDDDDDDDDDDuuuuuuuuuurDDDDDDDDDDuuuuuuuuuurDDDDDDDDDDuuuuuuuuuurDDDDDDDDDDuuuuuuuuuurDDDDDDDDDDuuuuuuuuuurDDDDDDDDDDDDuuuuuuuuuuuurDDDDDDDDDDDDDuuuuuuuuuuuuurDDDDDDDDDDDDDuuuuuuuuuuuuurDDDDDDDDDDDDDuuuuuuuuuuuuurDDDDDDDDDDDDDuuuuuuuuuuuuurDlddrruLLLLulDDDDDDDDDDDuuuuuuuuuuuurrrrrDlddrruLLLLulDDDDDDDDDDDuuuuuuuuuuuurrrrrDlddrruLLLLulDDDDDDDDDDDuuuuuuuuuuuurrrrrDlddrruLLLLulDDDDDDDDDDDuuuuuuuuuuuurrrrrDlddrruLLLLLLLLLulDDDDDDDDDDuuuuuuuuuuurrrrrrrrrrDlddrruLLLLLLLLLulDDDDDDDDDDuuuuuuuuuuurrrrrrrrrrrrddLLLLLLLLLLulDDDDDDDDDDuuuuuuuuuuurrrrrrrrrDurrddlLLLLLLLLulDDDDDDDDDDuuuuuuuuurrrrrrrrrruLLLLLLLLulDDDDDDDDDDDuuuuuuuuurrrrrrrrrdLLLLLLLLLLLLulDDDDDDDDuuuuuuurrrrrrrrrrrrrdLLLLLLLLLLLulDDDDDDDuuuuuurrrrrrrrrrrrdLLLLLLLLLLulDDDDDDuuuuurrrrrrrrrrrdLLLLLLLLLulDDDDDuuuurrrrrrrrrrdLLLLLLLLulDDDDuuurrrrrrrrrddLLLLLLLLLLLLLLLLLulDrrrrrrrrrrrrrrrrrrdLLLLLLLLLLLLLLLLurrrrrrrrrrrrrrrruLLLLLLLLLLLLLLLulDDrrrrrrrrrrrrrrrrddLullddrUruLLLLLLLLLLLLLrrrrrrrrrrrrrrddLullddrUUruLLLLLLLLLLLLrrrrrrrrrrrrrdddLullddrUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddLullddrUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrddddddLullddrUUUUUruLLLLLLLLLLLrrrrrrrrrrrrddddddLullddrUUUUUUruLLLLLLLLLLrrrrrrrrrrrdddddddLullddrUUUUUUUruLLLLLLLLLrrrrrrrrrrddddddddLullddrUUUUUUUUruLLLLLLLLrrrrrrrrrdddddddddLullddrUUUUUUUUUruLLLLLLLrrrrrrrrddddddddddLullddrUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLulDuuuuuuuullllllllllDrddlluRRRRRRRRRRRRurDDDDDDDuuuuuuuulllllllllllllDrddlluRRRRRRRRRRRRRRurDDDDDDDuuuuuuuulllllllllllllllllllllddRRRRRRRRRRRRRRRRRRRRRurDDDDDDDuuuuuulllllllllllllllllllllldRRRRRRRRRRRRRRRRRRRRRRurDDDDDDuuuuullllllllllllllllllllllldRRRRRRRRRRRRRRRRRRRRRRRurDDDDDuuuulllllllllllllllllllllllldRurrddlUluRRRRRRRRRRRRRRRRRRRRRRRurDDDDDuuuuuuuulllllllllllllllllllllllllllddddRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDuuuuuuuulllllllllllllllllllllllllDldRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDDDuuuuuuuulllllllllllllllllllllllllDldRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDDDuuuuuuuulllllllllllllllllllllllllDldRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDDDuuuuuuuulllllllllllllllllllllllllDldRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDDDuuuuuuuulllllllllllllllllllllllllDldRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDDDuuuuuulllllllllllllllllllllllllluRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDDDDuuuullllllllllllllllllllllllllllllllddRurrddlUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDDDrrrrrrrrrrrrrdddddddddddddLullddrUUUUUUUUUUUUruLLLLLLLLLLrrrrrrrrrrrdddddddddddddLullddrUUUUUUUUUUUUUruLLLLLLLLLrrrrrrrrrrddddddddddddddLullddrUUUUUUUUUUUUUUruLLLLLLLLrrrrrrrrrdddddddddddddddLullddrUUUUUUUUUUUUUUUruLLLLLLLrrrrrrrrddddddddddddddddLullddrUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddLullddrUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddLullddrUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddLullddrUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddLullddrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddllUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddLullddrUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddrUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLrrrrrrrrrrrrrddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLrrrrrrrrrrrddddddddddddddddddddddddlUUUluRdrUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLrrrrrrrrrrddddddddddddddddddddlddddlUUUluRRdrUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLrrrrrrrrrddddddddddddddddddddllddddlUUUluRRRdrUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLrrrrrrrrddddddddddddddddddddlllddddlUUUluRRRRdrUUUUUUUUUUUUUUUUUUUUruLLLLLLLLrrrrrrrddddddddddddddddddddllllddddlUUUluRRRRRdrUUUUUUUUUUUUUUUUUUUUruLLLLLLLrrrrrrddddddddddddddddddddlllllddddllUUUluRRRRRRRdrUUUUUUUUUUUUUUUUUUUUruLLLLLLrrrrrddddddddddddddddddddlllllllddddlUUUluRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUruLLLLLrrrrddddddddddddddddddddllllllllddddlllUUUluRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUruLLLLrrrddddddddddddddddddddllllllllddddllUUUluRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUruLLLrrddddddddddddddddddddllllllllddddlUUUluRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUruLLrddddddddddddddddddddlllllddddlUUUluRRRRRRdrUUUUUUUUUUUUUUUUUUUUruLddddddddddddddddddddlllllllllllddddlUUUruLLLLLLLLLLLLLLLLLLLLdlUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRurDDDuulllllllllllllluuuRRRRRRRRRRRRRRurDDDDDDuullllllllllllllluuRRRRRRRRRRRRRRRurDDDDDuulllllllllllllllluRRRRRRRRRRRRRRRRurDDDDuullllllllllllllldddRurrddlUUUluRRRRRRRRRRRRRRurDDDuulllllllllllllllllldRurrddlUluRRRRRRRRRRRRRRRRRurDDDuulllllllllllllllllllddRurrddlUUluRRRRRRRRRRRRRRRRRRurDDDrrrrrrrrrrrrrrrrrrrrddddddddddddddddddddddllllllllllllddddlUUUluRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrrdddddddddddddddddddddlllllllllllllddddlUUUluRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrrdddddddddddddddddddddllllllllllllllddddlUUUluRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrrdddddddddddddddddddddlllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLLrrrrrrrrrrrrrrrdddddddddddddddddddddllllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLLrrrrrrrrrrrrrrdddddddddddddddddddddlllllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLLrrrrrrrrrrrrrdddddddddddddddddddddllllllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLLrrrrrrrrrrrrdddddddddddddddddddddlllllllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLLrrrrrrrrrrrdddddddddddddddddddddllllllllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLLrrrrrrrrrrdddddddddddddddddddddlllllllllllllllllllllddddllUUUluRRRRRRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLLrrrrrrrrrdddddddddddddddddddddlllllllllllllllllllllllddddllUUUluRRRRRRRRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLLrrrrrrrrdddddddddddddddddddddlllllllllllllllllllllllllddddllUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLLrrrrrrrdddddddddddddddddddddlllllllllllllllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRdrUUUUUUUUUUUUUUUUUUUUUruLLLLLLLuuulllllllllllllllllllllllllllllllldddddRluurrrdddlUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDuulllllllllllllllllllllllllllllllldddddddRluurrrdddlUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDuullllllllllllllllllllllllllllllllldddddddddRluurrrdddlUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDuulllllllllllllllllllllllllllllllllldddddddddddRluurrrdddlUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDuullllllllllllllllllllllllllllllllldddddddddlUluRdrUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDuullllllllllllllllllllllllllllllllllllllddddRluurrrrdddllUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDDrddddddddddddddddddddddllllllllllllllllllllllllllllddddllUUUruLLdlUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRurDDulllllllllldddddddlUluRdrUUUUUluRRRRRRRRRRRurDDulllllllllllllllddddddRluurrdrddlUUUUUUluRRRRRRRRRRRRRRurDDullllllllllllllllddddddddRluurrrdddlUUUUUUUUluRRRRRRRRRRRRRRRurDDullllllllllllldddddddddddlUUUUUluRdrUUUUUluRRRRRRRRRRRRRRurDDulllllllllllllldddddlUUUUluRRRRRRRRRRRRRRRRurDDulllllllllllllllllddddddlUluRdrUUUUluRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllddddddddlUUUluRdrUUUUluRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllddddddddddRluurrrdddlUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllldddddddddddddRluurrrdddlUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllldddddddddddddddRluurrrdddlUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllldddddddddddddddddRluurrrdddlUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllllldddddddddddddddddddRluurrrdddlUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllldddddddddddddddddddddRldddrruuUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllllllldddddddddddddddddddddddRdrUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllllllllllllllllddddlUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllllllllllllllllllddddddddddlUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllllllllllllllldddddddddddddlUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllllllllllllllllllddddddddddddRluurrrdddlUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllllllldddddddddddddRurrrdddlluUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllllllddddddddddddlUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllllldddddddddddddddlUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllllllllllllldddddddddddddddRluurrrrddddlluUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllllllldddddddddddddddddlUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllllllllllllddddddddddddddddRurrddlUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDulllllllllllllllllllllllllllllllllldddddddddddddddddddRluuurrrrdddddlluUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRurDlllllllllllldddddddddddddddlUUUUUUUUUUUUUUluRRRRRRRRRRRRRRurDllllllllllldddddddddddddddddddlUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDDullllllllllllllllllllllllllllllllllldddddddddddddddddRurrddlUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllllllllllllllllllldddddddddddddddddddlUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRurDllllllllddddddddddddddddddddddddrrddddlllllUUUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllllllllllllddddddddddddddddddddddddddddrrUUUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllllllllllllllddddddddddddddddddddddddddddllUUUUluRdrUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllllllllllllllldddddddddddddddddddddddddRldddrrruulUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllllllllllddddddddddddddddddddddddddddrUUUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllllllllllllldddddddddddddddddddddRlddddrruuuUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRurDllllllllllllllllldddddddddddddddddddddddRlddrruUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllllddddddddddddddddddddddddrrrrrddddrUUUruLLLLLLdlUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRurDlllllllllllllldddddddddddddddddddddddlUluRdrUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllllllddddddddddddddddddddddddddddrUUUruLdlUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRurDllllllllllllddddddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllllllllldddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRurDlllllllllllllllllddddddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllllllldddddddddddddddddddddddddlUluRdrUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllllllllddddddddddddddddddddddddddRurrddlUUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRurDlllllllllllllddddddddddddddddddddddddrrrrrrrrrddddrUUUruLLLLLLLLLLdlUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllddddddddddddddddddddddddrrddddrUUUruLLLdlUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRurDllllllllllllllddddddddddddddddddddddddrrrrrrrddddrUUUruLLLLLLLLdlUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllllddddddddddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllldddddddddddddddddddddddlUluRdrUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRurDlllllllllllllllllllllllddddddddddddddddddddddddddddlUUUUUUluRdrUUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRurDllllllllllllllllllllldddddddddddddddddddddlUUUUUUUUUUUUUUUUUUUUluRRRRRRRRRRRRRRRRRRRRRRRurD",
      "layout": [
        "###################################################",
        "#    @                                            #",
        "# $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ #",
        "# $ $                                           $ #",
        "# $ $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $ #",
        "# $ $ $                                       $ $ #",
        "# $ $ $ $ ******************************* $ $ $ $ #",
        "# $ $ $ $ *.............................* $ $ $ $ #",
        "# $ $ $ $ *.*.*************************.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.......................*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*********************.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*...................*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*.*****************.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*.*...............*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*........*........*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*........*........*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*........*........*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*.....*******.....*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*........*........*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*........*........*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*........*........*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*.................*.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.*******************.*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.*.....................*.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.***********************.*.* $ $ $ $ #",
        "# $ $ $ $ *.*.........................*.* $ $ $ $ #",
        "# $ $ $ $ *.***************************.* $ $ $ $ #",
        "# $ $ $ $ *.............................* $ $ $ $ #",
        "# $ $ $ $ ******************************* $ $ $ $ #",
        "# $ $                                         $ $ #",
        "# $ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $ #",
        "# $                                             $ #",
        "# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ #",
        "#                                                 #",
        "###################################################"
      ],
      "rainbowMode": true,
      "goalColours": {
        "10,6": "blue",
        "11,6": "blue",
        "12,6": "yellow",
        "13,6": "yellow",
        "14,6": "blue",
        "15,6": "blue",
        "16,6": "blue",
        "17,6": "yellow",
        "18,6": "blue",
        "19,6": "blue",
        "20,6": "orange",
        "21,6": "yellow",
        "22,6": "blue",
        "23,6": "blue",
        "24,6": "blue",
        "25,6": "yellow",
        "26,6": "yellow",
        "27,6": "blue",
        "28,6": "blue",
        "29,6": "blue",
        "30,6": "blue",
        "31,6": "blue",
        "32,6": "blue",
        "33,6": "blue",
        "34,6": "blue",
        "35,6": "blue",
        "36,6": "blue",
        "37,6": "blue",
        "38,6": "blue",
        "39,6": "blue",
        "40,6": "blue",
        "10,7": "blue",
        "11,7": "blue",
        "12,7": "yellow",
        "13,7": "orange",
        "14,7": "yellow",
        "15,7": "blue",
        "16,7": "yellow",
        "17,7": "orange",
        "18,7": "blue",
        "19,7": "blue",
        "20,7": "yellow",
        "21,7": "orange",
        "22,7": "blue",
        "23,7": "orange",
        "24,7": "blue",
        "25,7": "blue",
        "26,7": "blue",
        "27,7": "blue",
        "28,7": "blue",
        "29,7": "yellow",
        "30,7": "blue",
        "31,7": "blue",
        "32,7": "blue",
        "33,7": "blue",
        "34,7": "blue",
        "35,7": "blue",
        "36,7": "light-blue",
        "37,7": "light-blue",
        "38,7": "yellow",
        "39,7": "yellow",
        "40,7": "light-blue",
        "10,8": "blue",
        "11,8": "blue",
        "12,8": "blue",
        "13,8": "blue",
        "14,8": "blue",
        "15,8": "blue",
        "16,8": "blue",
        "17,8": "blue",
        "18,8": "blue",
        "19,8": "blue",
        "20,8": "blue",
        "21,8": "blue",
        "22,8": "blue",
        "23,8": "blue",
        "24,8": "blue",
        "25,8": "blue",
        "26,8": "blue",
        "27,8": "blue",
        "28,8": "yellow",
        "29,8": "yellow",
        "30,8": "yellow",
        "31,8": "blue",
        "32,8": "blue",
        "33,8": "blue",
        "34,8": "blue",
        "35,8": "light-blue",
        "36,8": "yellow",
        "37,8": "orange",
        "38,8": "orange",
        "39,8": "yellow",
        "40,8": "yellow",
        "10,9": "light-blue",
        "11,9": "blue",
        "12,9": "blue",
        "13,9": "blue",
        "14,9": "blue",
        "15,9": "blue",
        "16,9": "yellow",
        "17,9": "yellow",
        "18,9": "yellow",
        "19,9": "blue",
        "20,9": "blue",
        "21,9": "blue",
        "22,9": "blue",
        "23,9": "light-blue",
        "24,9": "light-blue",
        "25,9": "light-blue",
        "26,9": "light-blue",
        "27,9": "light-blue",
        "28,9": "blue",
        "29,9": "blue",
        "30,9": "blue",
        "31,9": "blue",
        "32,9": "blue",
        "33,9": "blue",
        "34,9": "blue",
        "35,9": "light-blue",
        "36,9": "orange",
        "37,9": "orange",
        "38,9": "yellow",
        "39,9": "yellow",
        "40,9": "yellow",
        "10,10": "light-blue",
        "11,10": "light-blue",
        "12,10": "blue",
        "13,10": "blue",
        "14,10": "blue",
        "15,10": "blue",
        "16,10": "yellow",
        "17,10": "orange",
        "18,10": "yellow",
        "19,10": "blue",
        "20,10": "light-blue",
        "21,10": "light-blue",
        "22,10": "light-blue",
        "23,10": "light-blue",
        "24,10": "cream",
        "25,10": "light-blue",
        "26,10": "cream",
        "27,10": "cream",
        "28,10": "light-blue",
        "29,10": "blue",
        "30,10": "blue",
        "31,10": "blue",
        "32,10": "yellow",
        "33,10": "blue",
        "34,10": "blue",
        "35,10": "light-blue",
        "36,10": "orange",
        "37,10": "orange",
        "38,10": "yellow",
        "39,10": "yellow",
        "40,10": "orange",
        "10,11": "light-blue",
        "11,11": "light-blue",
        "12,11": "blue",
        "13,11": "blue",
        "14,11": "blue",
        "15,11": "blue",
        "16,11": "blue",
        "17,11": "yellow",
        "18,11": "blue",
        "19,11": "light-blue",
        "20,11": "light-blue",
        "21,11": "light-blue",
        "22,11": "cream",
        "23,11": "light-blue",
        "24,11": "light-blue",
        "25,11": "light-blue",
        "26,11": "light-blue",
        "27,11": "light-blue",
        "28,11": "light-blue",
        "29,11": "light-blue",
        "30,11": "blue",
        "31,11": "blue",
        "32,11": "orange",
        "33,11": "yellow",
        "34,11": "blue",
        "35,11": "light-blue",
        "36,11": "yellow",
        "37,11": "orange",
        "38,11": "orange",
        "39,11": "orange",
        "40,11": "yellow",
        "10,12": "light-blue",
        "11,12": "blue",
        "12,12": "light-blue",
        "13,12": "light-blue",
        "14,12": "light-blue",
        "15,12": "light-blue",
        "16,12": "burgundy",
        "17,12": "light-blue",
        "18,12": "light-blue",
        "19,12": "light-blue",
        "20,12": "light-blue",
        "21,12": "light-blue",
        "22,12": "blue",
        "23,12": "blue",
        "24,12": "blue",
        "25,12": "blue",
        "26,12": "blue",
        "27,12": "light-blue",
        "28,12": "cream",
        "29,12": "light-blue",
        "30,12": "light-blue",
        "31,12": "blue",
        "32,12": "blue",
        "33,12": "blue",
        "34,12": "blue",
        "35,12": "blue",
        "36,12": "light-blue",
        "37,12": "yellow",
        "38,12": "yellow",
        "39,12": "yellow",
        "40,12": "light-blue",
        "10,13": "light-blue",
        "11,13": "blue",
        "12,13": "light-blue",
        "13,13": "light-blue",
        "14,13": "cream",
        "15,13": "light-blue",
        "16,13": "brown",
        "17,13": "light-blue",
        "18,13": "light-blue",
        "19,13": "light-blue",
        "20,13": "orange",
        "21,13": "blue",
        "22,13": "blue",
        "23,13": "blue",
        "24,13": "blue",
        "25,13": "blue",
        "26,13": "blue",
        "27,13": "light-blue",
        "28,13": "light-blue",
        "29,13": "light-blue",
        "30,13": "light-blue",
        "31,13": "blue",
        "32,13": "blue",
        "33,13": "blue",
        "34,13": "blue",
        "35,13": "blue",
        "36,13": "light-blue",
        "37,13": "light-blue",
        "38,13": "light-blue",
        "39,13": "light-blue",
        "40,13": "light-blue",
        "10,14": "light-blue",
        "11,14": "light-blue",
        "12,14": "blue",
        "13,14": "light-blue",
        "14,14": "cream",
        "15,14": "light-blue",
        "16,14": "burgundy",
        "17,14": "light-blue",
        "18,14": "light-blue",
        "19,14": "blue",
        "20,14": "yellow",
        "21,14": "blue",
        "22,14": "blue",
        "23,14": "light-blue",
        "24,14": "light-blue",
        "25,14": "blue",
        "26,14": "light-blue",
        "27,14": "light-blue",
        "28,14": "light-blue",
        "29,14": "light-blue",
        "30,14": "blue",
        "31,14": "blue",
        "32,14": "blue",
        "33,14": "blue",
        "34,14": "blue",
        "35,14": "blue",
        "36,14": "blue",
        "37,14": "blue",
        "38,14": "blue",
        "39,14": "blue",
        "40,14": "blue",
        "10,15": "light-blue",
        "11,15": "light-blue",
        "12,15": "light-blue",
        "13,15": "cream",
        "14,15": "light-blue",
        "15,15": "burgundy",
        "16,15": "burgundy",
        "17,15": "blue",
        "18,15": "blue",
        "19,15": "blue",
        "20,15": "blue",
        "21,15": "blue",
        "22,15": "blue",
        "23,15": "light-blue",
        "24,15": "blue",
        "25,15": "blue",
        "26,15": "blue",
        "27,15": "light-blue",
        "28,15": "light-blue",
        "29,15": "blue",
        "30,15": "blue",
        "31,15": "light-blue",
        "32,15": "light-blue",
        "33,15": "blue",
        "34,15": "blue",
        "35,15": "blue",
        "36,15": "blue",
        "37,15": "blue",
        "38,15": "blue",
        "39,15": "blue",
        "40,15": "light-blue",
        "10,16": "blue",
        "11,16": "yellow",
        "12,16": "blue",
        "13,16": "blue",
        "14,16": "yellow",
        "15,16": "burgundy",
        "16,16": "black",
        "17,16": "burgundy",
        "18,16": "blue",
        "19,16": "blue",
        "20,16": "light-blue",
        "21,16": "light-blue",
        "22,16": "blue",
        "23,16": "blue",
        "24,16": "light-blue",
        "25,16": "light-blue",
        "26,16": "blue",
        "27,16": "blue",
        "28,16": "light-blue",
        "29,16": "light-blue",
        "30,16": "light-blue",
        "31,16": "blue",
        "32,16": "blue",
        "33,16": "light-blue",
        "34,16": "blue",
        "35,16": "blue",
        "36,16": "light-blue",
        "37,16": "light-blue",
        "38,16": "light-blue",
        "39,16": "light-blue",
        "40,16": "light-blue",
        "10,17": "blue",
        "11,17": "yellow",
        "12,17": "blue",
        "13,17": "yellow",
        "14,17": "yellow",
        "15,17": "burgundy",
        "16,17": "black",
        "17,17": "burgundy",
        "18,17": "blue",
        "19,17": "blue",
        "20,17": "yellow",
        "21,17": "yellow",
        "22,17": "light-blue",
        "23,17": "blue",
        "24,17": "blue",
        "25,17": "light-blue",
        "26,17": "light-blue",
        "27,17": "light-blue",
        "28,17": "light-blue",
        "29,17": "blue",
        "30,17": "blue",
        "31,17": "blue",
        "32,17": "light-blue",
        "33,17": "light-blue",
        "34,17": "blue",
        "35,17": "blue",
        "36,17": "light-blue",
        "37,17": "light-blue",
        "38,17": "cream",
        "39,17": "light-blue",
        "40,17": "light-blue",
        "10,18": "blue",
        "11,18": "blue",
        "12,18": "blue",
        "13,18": "blue",
        "14,18": "yellow",
        "15,18": "burgundy",
        "16,18": "black",
        "17,18": "burgundy",
        "18,18": "blue",
        "19,18": "blue",
        "20,18": "orange",
        "21,18": "orange",
        "22,18": "yellow",
        "23,18": "light-blue",
        "24,18": "blue",
        "25,18": "blue",
        "26,18": "blue",
        "27,18": "blue",
        "28,18": "blue",
        "29,18": "blue",
        "30,18": "blue",
        "31,18": "light-blue",
        "32,18": "light-blue",
        "33,18": "blue",
        "34,18": "blue",
        "35,18": "light-blue",
        "36,18": "light-blue",
        "37,18": "cream",
        "38,18": "light-blue",
        "39,18": "light-blue",
        "40,18": "blue",
        "10,19": "blue",
        "11,19": "blue",
        "12,19": "blue",
        "13,19": "blue",
        "14,19": "blue",
        "15,19": "burgundy",
        "16,19": "burgundy",
        "17,19": "burgundy",
        "18,19": "blue",
        "19,19": "blue",
        "20,19": "orange",
        "21,19": "orange",
        "22,19": "yellow",
        "23,19": "light-blue",
        "24,19": "blue",
        "25,19": "blue",
        "26,19": "blue",
        "27,19": "blue",
        "28,19": "blue",
        "29,19": "blue",
        "30,19": "blue",
        "31,19": "light-blue",
        "32,19": "light-blue",
        "33,19": "light-blue",
        "34,19": "light-blue",
        "35,19": "light-blue",
        "36,19": "light-blue",
        "37,19": "light-blue",
        "38,19": "light-blue",
        "39,19": "blue",
        "40,19": "blue",
        "10,20": "light-blue",
        "11,20": "light-blue",
        "12,20": "light-blue",
        "13,20": "light-blue",
        "14,20": "burgundy",
        "15,20": "burgundy",
        "16,20": "brown",
        "17,20": "burgundy",
        "18,20": "burgundy",
        "19,20": "burgundy",
        "20,20": "light-blue",
        "21,20": "light-blue",
        "22,20": "light-blue",
        "23,20": "light-blue",
        "24,20": "light-blue",
        "25,20": "light-blue",
        "26,20": "light-blue",
        "27,20": "light-blue",
        "28,20": "light-blue",
        "29,20": "light-blue",
        "30,20": "light-blue",
        "31,20": "light-blue",
        "32,20": "light-blue",
        "33,20": "blue",
        "34,20": "blue",
        "35,20": "blue",
        "36,20": "blue",
        "37,20": "blue",
        "38,20": "blue",
        "39,20": "blue",
        "40,20": "blue",
        "10,21": "cream",
        "11,21": "cream",
        "12,21": "light-blue",
        "13,21": "light-blue",
        "14,21": "light-blue",
        "15,21": "burgundy",
        "16,21": "brown",
        "17,21": "burgundy",
        "18,21": "burgundy",
        "19,21": "burgundy",
        "20,21": "light-blue",
        "21,21": "cream",
        "22,21": "light-blue",
        "23,21": "light-blue",
        "24,21": "light-blue",
        "25,21": "light-blue",
        "26,21": "light-blue",
        "27,21": "light-blue",
        "28,21": "light-blue",
        "29,21": "blue",
        "30,21": "blue",
        "31,21": "blue",
        "32,21": "blue",
        "33,21": "blue",
        "34,21": "blue",
        "35,21": "blue",
        "36,21": "blue",
        "37,21": "blue",
        "38,21": "blue",
        "39,21": "blue",
        "40,21": "blue",
        "10,22": "cream",
        "11,22": "light-blue",
        "12,22": "light-blue",
        "13,22": "light-blue",
        "14,22": "light-blue",
        "15,22": "black",
        "16,22": "brown",
        "17,22": "burgundy",
        "18,22": "burgundy",
        "19,22": "burgundy",
        "20,22": "light-blue",
        "21,22": "light-blue",
        "22,22": "light-blue",
        "23,22": "light-blue",
        "24,22": "blue",
        "25,22": "blue",
        "26,22": "light-blue",
        "27,22": "light-blue",
        "28,22": "blue",
        "29,22": "blue",
        "30,22": "blue",
        "31,22": "blue",
        "32,22": "blue",
        "33,22": "blue",
        "34,22": "blue",
        "35,22": "blue",
        "36,22": "blue",
        "37,22": "blue",
        "38,22": "blue",
        "39,22": "blue",
        "40,22": "blue",
        "10,23": "light-blue",
        "11,23": "blue",
        "12,23": "blue",
        "13,23": "light-blue",
        "14,23": "light-blue",
        "15,23": "black",
        "16,23": "brown",
        "17,23": "burgundy",
        "18,23": "burgundy",
        "19,23": "brown",
        "20,23": "burgundy",
        "21,23": "burgundy",
        "22,23": "blue",
        "23,23": "blue",
        "24,23": "blue",
        "25,23": "blue",
        "26,23": "blue",
        "27,23": "blue",
        "28,23": "blue",
        "29,23": "blue",
        "30,23": "blue",
        "31,23": "blue",
        "32,23": "blue",
        "33,23": "blue",
        "34,23": "teal",
        "35,23": "black",
        "36,23": "black",
        "37,23": "teal",
        "38,23": "blue",
        "39,23": "blue",
        "40,23": "teal",
        "10,24": "green",
        "11,24": "teal",
        "12,24": "teal",
        "13,24": "green",
        "14,24": "black",
        "15,24": "brown",
        "16,24": "brown",
        "17,24": "burgundy",
        "18,24": "burgundy",
        "19,24": "burgundy",
        "20,24": "brown",
        "21,24": "brown",
        "22,24": "burgundy",
        "23,24": "green",
        "24,24": "black",
        "25,24": "black",
        "26,24": "black",
        "27,24": "teal",
        "28,24": "teal",
        "29,24": "teal",
        "30,24": "teal",
        "31,24": "teal",
        "32,24": "teal",
        "33,24": "teal",
        "34,24": "teal",
        "35,24": "teal",
        "36,24": "teal",
        "37,24": "teal",
        "38,24": "teal",
        "39,24": "teal",
        "40,24": "teal",
        "10,25": "teal",
        "11,25": "teal",
        "12,25": "green",
        "13,25": "green",
        "14,25": "black",
        "15,25": "brown",
        "16,25": "burgundy",
        "17,25": "burgundy",
        "18,25": "burgundy",
        "19,25": "burgundy",
        "20,25": "brown",
        "21,25": "brown",
        "22,25": "brown",
        "23,25": "black",
        "24,25": "black",
        "25,25": "black",
        "26,25": "grey",
        "27,25": "grey",
        "28,25": "black",
        "29,25": "black",
        "30,25": "teal",
        "31,25": "teal",
        "32,25": "black",
        "33,25": "black",
        "34,25": "black",
        "35,25": "black",
        "36,25": "teal",
        "37,25": "teal",
        "38,25": "teal",
        "39,25": "green",
        "40,25": "black",
        "10,26": "teal",
        "11,26": "teal",
        "12,26": "green",
        "13,26": "green",
        "14,26": "black",
        "15,26": "burgundy",
        "16,26": "burgundy",
        "17,26": "brown",
        "18,26": "burgundy",
        "19,26": "burgundy",
        "20,26": "brown",
        "21,26": "brown",
        "22,26": "brown",
        "23,26": "brown",
        "24,26": "green",
        "25,26": "green",
        "26,26": "grey",
        "27,26": "grey",
        "28,26": "grey",
        "29,26": "black",
        "30,26": "black",
        "31,26": "black",
        "32,26": "black",
        "33,26": "lime",
        "34,26": "black",
        "35,26": "black",
        "36,26": "green",
        "37,26": "teal",
        "38,26": "teal",
        "39,26": "green",
        "40,26": "green",
        "10,27": "green",
        "11,27": "green",
        "12,27": "teal",
        "13,27": "teal",
        "14,27": "black",
        "15,27": "black",
        "16,27": "burgundy",
        "17,27": "brown",
        "18,27": "burgundy",
        "19,27": "burgundy",
        "20,27": "black",
        "21,27": "brown",
        "22,27": "burgundy",
        "23,27": "brown",
        "24,27": "black",
        "25,27": "green",
        "26,27": "green",
        "27,27": "green",
        "28,27": "black",
        "29,27": "grey",
        "30,27": "black",
        "31,27": "green",
        "32,27": "green",
        "33,27": "green",
        "34,27": "black",
        "35,27": "black",
        "36,27": "green",
        "37,27": "green",
        "38,27": "green",
        "39,27": "green",
        "40,27": "green",
        "10,28": "green",
        "11,28": "teal",
        "12,28": "teal",
        "13,28": "teal",
        "14,28": "teal",
        "15,28": "teal",
        "16,28": "brown",
        "17,28": "brown",
        "18,28": "burgundy",
        "19,28": "burgundy",
        "20,28": "black",
        "21,28": "brown",
        "22,28": "burgundy",
        "23,28": "brown",
        "24,28": "burgundy",
        "25,28": "teal",
        "26,28": "teal",
        "27,28": "teal",
        "28,28": "green",
        "29,28": "black",
        "30,28": "grey",
        "31,28": "grey",
        "32,28": "black",
        "33,28": "grey",
        "34,28": "grey",
        "35,28": "black",
        "36,28": "black",
        "37,28": "black",
        "38,28": "black",
        "39,28": "teal",
        "40,28": "teal"
      }
    }
  ]
};
  const current = Array.isArray(window.BOXXY_LEVEL_PACKS) ? window.BOXXY_LEVEL_PACKS : [];
  window.BOXXY_LEVEL_PACKS = [...current.filter(item => item?.id !== pack.id), pack];
})();
